PFASST++: pfasst::mpi::MPIError Class Reference
pfasst::mpi::MPIError Class Reference
#include <mpi_communicator.hpp>
Public Member Functions
MPIError (const string &msg="")
virtual const char * what () const throw ()
Static Public Member Functions
static MPIError from_code (const int err_code)
Detailed Description
Definition at line 43 of file mpi_communicator.hpp.
Constructor & Destructor Documentation
pfasst::mpi::MPIError::MPIError (const string & msg = "")
Definition at line 10 of file mpi_communicator_impl.hpp.
Referenced by from_code().
Member Function Documentation
MPIError pfasst::mpi::MPIError::from_code (const int err_code) static
Definition at line 19 of file mpi_communicator_impl.hpp.
References pfasst::mpi::check_mpi_error(), and MPIError().
const char * pfasst::mpi::MPIError::what () const throw () virtual
Definition at line 14 of file mpi_communicator_impl.hpp.
The documentation for this class was generated from the following files:
include/pfasst/mpi_communicator.hpp
src/pfasst/mpi_communicator_impl.hpp