PFASST++: Utilities
Utilities
Examples » Boris
Functions
template<typename precision >
static precision pfasst::examples::boris::distance (const Particle< precision > &first, const Particle< precision > &second)
template<typename precision >
static precision pfasst::examples::boris::distance (const shared_ptr< Particle< precision >> &first, const shared_ptr< Particle< precision >> &second)
template<typename precision >
static vector< precision > pfasst::examples::boris::distance_to_reference (const ParticleCloud< precision > &cloud, const Particle< precision > &reference)
template<typename precision >
static vector< precision > pfasst::examples::boris::distance_to_reference (const shared_ptr< ParticleCloud< precision >> &cloud, const shared_ptr< Particle< precision >> &reference)
template<typename precision >
pfasst::examples::boris::MAKE_LOGGABLE (shared_ptr< const ParticleCloud< precision >>, sp_cloud, os)
template<typename precision >
static vector< precision > pfasst::examples::boris::cloud_component_factory (const size_t num_particles, const size_t dim)
template<typename precision >
static void pfasst::examples::boris::zero (vector< precision > &data)
template<typename precision >
static void pfasst::examples::boris::zero (shared_ptr< vector< precision >> &data)
template<typename precision >
static vector< precision > pfasst::examples::boris::cross_prod (const vector< precision > &first, const vector< precision > &second)
template<typename precision >
static void pfasst::examples::boris::cross_prod_1part (typename vector< precision >::const_iterator __first, typename vector< precision >::const_iterator __second, typename vector< precision >::iterator __result)
template<typename precision >
static vector< precision > pfasst::examples::boris::cross_prod_npart (const vector< precision > &first, const vector< precision > &second)
template<typename precision >
static vector< precision > pfasst::examples::boris::kronecker (const vector< precision > &first, const vector< precision > &second)
template<typename precision >
static vector< precision > pfasst::examples::boris::cmp_wise_mul (const vector< precision > &first, const vector< precision > &second)
template<typename precision >
static vector< precision > pfasst::examples::boris::cmp_wise_div (const vector< precision > &first, const vector< precision > &second)
template<typename precision >
static precision pfasst::examples::boris::max (const vector< precision > &data)
template<typename precision >
static precision pfasst::examples::boris::max_abs (const vector< precision > &data)
template<typename precision >
static precision pfasst::examples::boris::norm_sq (const vector< precision > &data)
template<typename precision >
static precision pfasst::examples::boris::norm_sq (typename vector< precision >::const_iterator __first, typename vector< precision >::const_iterator __second)
template<typename precision >
static vector< precision > pfasst::examples::boris::norm_sq_npart (const vector< precision > &data, const size_t npart)
template<typename precision >
static precision pfasst::examples::boris::norm0 (const vector< precision > &data)
template<typename precision >
static precision pfasst::examples::boris::norm0 (typename vector< precision >::const_iterator __first, typename vector< precision >::const_iterator __second)
template<typename precision >
static vector< precision > pfasst::examples::boris::norm0_npart (const vector< precision > &data, const size_t npart)
template<typename precision >
vector< precision > pfasst::examples::boris::operator+ (const vector< precision > &first, const vector< precision > &second)
template<typename precision , typename ValueT >
vector< precision > pfasst::examples::boris::operator+ (const vector< precision > &vec, const ValueT &value)
template<typename precision , typename ValueT >
vector< precision > pfasst::examples::boris::operator+ (const ValueT &value, const vector< precision > &vec)
template<typename precision >
vector< precision > & pfasst::examples::boris::operator+= (vector< precision > &first, const vector< precision > &second)
template<typename precision , typename ValueT >
vector< precision > & pfasst::examples::boris::operator+= (vector< precision > &vec, const ValueT &value)
template<typename precision >
vector< precision > pfasst::examples::boris::operator- (const vector< precision > &first, const vector< precision > &second)
template<typename precision , typename ValueT >
vector< precision > pfasst::examples::boris::operator- (const vector< precision > &vec, const ValueT &value)
template<typename precision >
vector< precision > & pfasst::examples::boris::operator-= (vector< precision > &first, const vector< precision > &second)
template<typename precision , typename ValueT >
vector< precision > & pfasst::examples::boris::operator-= (vector< precision > &vec, const ValueT &value)
template<typename precision , typename ValueT >
vector< precision > pfasst::examples::boris::operator* (const vector< precision > &vec, const ValueT &value)
template<typename precision , typename ValueT >
vector< precision > pfasst::examples::boris::operator* (const ValueT &value, const vector< precision > &vec)
template<typename precision >
vector< precision > pfasst::examples::boris::operator* (const vector< precision > &vec, const vector< precision > &values)
template<typename precision , typename ValueT >
vector< precision > & pfasst::examples::boris::operator*= (vector< precision > &vec, const ValueT &value)
template<typename precision , typename ValueT >
vector< precision > pfasst::examples::boris::operator/ (const vector< precision > &vec, const ValueT &value)
template<typename precision >
vector< precision > pfasst::examples::boris::operator/ (const vector< precision > &vec, const vector< precision > &values)
template<typename precision , typename ValueT >
vector< precision > & pfasst::examples::boris::operator/= (vector< precision > &vec, const ValueT &value)
Detailed Description
Function Documentation
template<typename precision > static vector<precision> pfasst::examples::boris::cloud_component_factory (const size_t num_particles, const size_t dim) inline static
template<typename precision > static vector<precision> pfasst::examples::boris::cmp_wise_div (const vector< precision > & first, const vector< precision > & second) inline static
Referenced by pfasst::examples::boris::BorisSweeper< scalar, time >::boris_solve().
template<typename precision > static vector<precision> pfasst::examples::boris::cmp_wise_mul (const vector< precision > & first, const vector< precision > & second) inline static
template<typename precision > static vector<precision> pfasst::examples::boris::cross_prod (const vector< precision > & first, const vector< precision > & second) inline static
Referenced by pfasst::examples::boris::BorisSweeper< scalar, time >::boris_solve().
template<typename precision > static void pfasst::examples::boris::cross_prod_1part (typename vector< precision >::const_iterator __first, typename vector< precision >::const_iterator __second, typename vector< precision >::iterator __result) inline static
template<typename precision > static vector<precision> pfasst::examples::boris::cross_prod_npart (const vector< precision > & first, const vector< precision > & second) inline static
template<typename precision > static precision pfasst::examples::boris::distance (const Particle< precision > & first, const Particle< precision > & second) static
Referenced by pfasst::examples::boris::distance(), and pfasst::examples::boris::distance_to_reference().
template<typename precision > static precision pfasst::examples::boris::distance (const shared_ptr< Particle< precision >> & first, const shared_ptr< Particle< precision >> & second) static
template<typename precision > static vector<precision> pfasst::examples::boris::distance_to_reference (const ParticleCloud< precision > & cloud, const Particle< precision > & reference) static
Referenced by pfasst::examples::boris::distance_to_reference(), and TEST().
template<typename precision > static vector<precision> pfasst::examples::boris::distance_to_reference (const shared_ptr< ParticleCloud< precision >> & cloud, const shared_ptr< Particle< precision >> & reference) static
template<typename precision > static vector<precision> pfasst::examples::boris::kronecker (const vector< precision > & first, const vector< precision > & second) inline static
Referenced by pfasst::examples::boris::BorisSweeper< scalar, time >::boris_solve().
template<typename precision > pfasst::examples::boris::MAKE_LOGGABLE (shared_ptr< ParticleCloud< precision >> , sp_cloud , os) inline
Definition at line 460 of file particle_cloud_impl.hpp.
template<typename precision > static precision pfasst::examples::boris::max (const vector< precision > & data) inline static
Referenced by pfasst::examples::boris::BorisSweeper< scalar, time >::compute_residual_max(), pfasst::examples::boris::ParticleCloud< precision >::distribute_around_center(), pfasst::examples::vdp::VdpSweeper< time >::echo_error(), pfasst::examples::advection_diffusion::AdvectionDiffusionSweeper< time >::echo_error(), and pfasst::examples::boris::ParticleCloud< precision >::norm0().
template<typename precision > static precision pfasst::examples::boris::max_abs (const vector< precision > & data) inline static
Referenced by pfasst::examples::boris::ParticleCloud< precision >::norm0().
template<typename precision > static precision pfasst::examples::boris::norm0 (const vector< precision > & data) inline static
Referenced by pfasst::encap::EncapSweeper< time >::converged(), and pfasst::examples::boris::distance().
template<typename precision > static precision pfasst::examples::boris::norm0 (typename vector< precision >::const_iterator __first, typename vector< precision >::const_iterator __second) inline static
template<typename precision > static vector<precision> pfasst::examples::boris::norm0_npart (const vector< precision > & data, const size_t npart) inline static
template<typename precision > static precision pfasst::examples::boris::norm_sq (const vector< precision > & data) inline static
template<typename precision > static precision pfasst::examples::boris::norm_sq (typename vector< precision >::const_iterator __first, typename vector< precision >::const_iterator __second) inline static
template<typename precision > static vector<precision> pfasst::examples::boris::norm_sq_npart (const vector< precision > & data, const size_t npart) inline static
Referenced by pfasst::examples::boris::BorisSweeper< scalar, time >::boris_solve().
template<typename precision , typename ValueT > vector< precision > pfasst::examples::boris::operator* (const vector< precision > & vec, const ValueT & value) inline
Definition at line 334 of file particle_util_impl.hpp.
template<typename precision , typename ValueT > vector< precision > pfasst::examples::boris::operator* (const ValueT & value, const vector< precision > & vec) inline
Definition at line 343 of file particle_util_impl.hpp.
References ML_LOG.
template<typename precision > vector< precision > pfasst::examples::boris::operator* (const vector< precision > & vec, const vector< precision > & values) inline
Definition at line 352 of file particle_util_impl.hpp.
template<typename precision , typename ValueT > vector< precision > & pfasst::examples::boris::operator*= (vector< precision > & vec, const ValueT & value) inline
Definition at line 368 of file particle_util_impl.hpp.
template<typename precision > vector< precision > pfasst::examples::boris::operator+ (const vector< precision > & first, const vector< precision > & second) inline
Definition at line 187 of file particle_util_impl.hpp.
References ML_LOG.
template<typename precision , typename ValueT > vector< precision > pfasst::examples::boris::operator+ (const vector< precision > & vec, const ValueT & value) inline
Definition at line 210 of file particle_util_impl.hpp.
template<typename precision , typename ValueT > vector< precision > pfasst::examples::boris::operator+ (const ValueT & value, const vector< precision > & vec) inline
Definition at line 219 of file particle_util_impl.hpp.
References ML_LOG.
template<typename precision > vector< precision > & pfasst::examples::boris::operator+= (vector< precision > & first, const vector< precision > & second) inline
Definition at line 232 of file particle_util_impl.hpp.
template<typename precision , typename ValueT > vector< precision > & pfasst::examples::boris::operator+= (vector< precision > & vec, const ValueT & value) inline
Definition at line 251 of file particle_util_impl.hpp.
template<typename precision > vector< precision > pfasst::examples::boris::operator- (const vector< precision > & first, const vector< precision > & second) inline
Definition at line 265 of file particle_util_impl.hpp.
template<typename precision , typename ValueT > vector< precision > pfasst::examples::boris::operator- (const vector< precision > & vec, const ValueT & value) inline
Definition at line 288 of file particle_util_impl.hpp.
template<typename precision > vector< precision > & pfasst::examples::boris::operator-= (vector< precision > & first, const vector< precision > & second) inline
Definition at line 301 of file particle_util_impl.hpp.
template<typename precision , typename ValueT > vector< precision > & pfasst::examples::boris::operator-= (vector< precision > & vec, const ValueT & value) inline
Definition at line 320 of file particle_util_impl.hpp.
template<typename precision , typename ValueT > vector< precision > pfasst::examples::boris::operator/ (const vector< precision > & vec, const ValueT & value) inline
Definition at line 382 of file particle_util_impl.hpp.
template<typename precision > vector< precision > pfasst::examples::boris::operator/ (const vector< precision > & vec, const vector< precision > & values) inline
Definition at line 391 of file particle_util_impl.hpp.
template<typename precision , typename ValueT > vector< precision > & pfasst::examples::boris::operator/= (vector< precision > & vec, const ValueT & value) inline
Definition at line 407 of file particle_util_impl.hpp.
template<typename precision > static void pfasst::examples::boris::zero (vector< precision > & data) inline static
Referenced by pfasst::examples::boris::InjectiveTransfer< scalar, time >::fas(), pfasst::examples::boris::BorisSweeper< scalar, time >::integrate(), pfasst::examples::boris::BorisSweeper< scalar, time >::residual(), pfasst::examples::boris::BorisSweeper< scalar, time >::sweep(), and pfasst::examples::boris::BorisSweeper< scalar, time >::update_velocity().
template<typename precision > static void pfasst::examples::boris::zero (shared_ptr< vector< precision >> & data) inline static