PFASST++: pfasst::quadrature::Polynomial< CoeffT > Class Template Reference
pfasst::quadrature::Polynomial< CoeffT > Class Template Reference
Representation of a polynomial including differentiation, integration and root finding.
#include <polynomial.hpp>
Public Member Functions
Polynomial (size_t n)
size_t order () const
Order of this polynomial.
CoeffT & operator[] (const size_t i)
Access coefficient i.
Polynomial< CoeffT > differentiate () const
Differentiate this polynomial.
Polynomial< CoeffT > integrate () const
Integrates this polynomial.
template<typename xtype >
xtype evaluate (const xtype x) const
Evaluate polynomial for given value.
Polynomial< CoeffT > normalize () const
Normalizes this polynomial with respect to \(c_0 \).
vector< CoeffT > roots (size_t num_iterations=100, CoeffT ztol=1.0e-20) const
Computes the roots of this polynomial.
Static Public Member Functions
static Polynomial< CoeffT > legendre (const size_t order)
Computes the Legendre polynomial of given order.
Protected Attributes
vector< CoeffT > c
Coefficients of the polynomial.
Detailed Description
template<typename CoeffT>
class pfasst::quadrature::Polynomial< CoeffT >
Representation of a polynomial including differentiation, integration and root finding.
Nothing more than a \(n \)-th order polynomial of the form \(P_n(x) = \sum_{i=0}^{n} c_i x^i \) with coefficients \(c_i \), \(i=0, \dots, n \).
Template Parameters
CoeffT numerical precision of polynomial coefficients (e.g. double)
Since
v0.3.0
Definition at line 28 of file polynomial.hpp.
Constructor & Destructor Documentation
template<typename CoeffT > pfasst::quadrature::Polynomial< CoeffT >::Polynomial (size_t n)
Todo:
Consider issuing a warning/assertion when n is zero.
Definition at line 18 of file polynomial_impl.hpp.
Member Function Documentation
template<typename CoeffT > Polynomial< CoeffT > pfasst::quadrature::Polynomial< CoeffT >::differentiate () const
Differentiate this polynomial.
Computes standard differential of this polynomial.
Returns
differentiated polynomial
Definition at line 35 of file polynomial_impl.hpp.
template<typename CoeffT> template<typename xtype > xtype pfasst::quadrature::Polynomial< CoeffT >::evaluate (const xtype x) const inline
Evaluate polynomial for given value.
Template Parameters
xtype numerical type of the value
Parameters
[in] x value to evaluate polynomial at
Returns
value of polynomial at x
Definition at line 95 of file polynomial.hpp.
Referenced by pfasst::quadrature::compute_q_matrix(), pfasst::quadrature::compute_q_vec(), and pfasst::quadrature::Polynomial< CoeffT >::roots().
template<typename CoeffT > Polynomial< CoeffT > pfasst::quadrature::Polynomial< CoeffT >::integrate () const
Integrates this polynomial.
Computes integral of this polynomial.
Returns
integrated polynomial
Definition at line 45 of file polynomial_impl.hpp.
Referenced by pfasst::quadrature::compute_q_matrix(), and pfasst::quadrature::compute_q_vec().
template<typename CoeffT > Polynomial< CoeffT > pfasst::quadrature::Polynomial< CoeffT >::legendre (const size_t order) static
Computes the Legendre polynomial of given order.
Parameters
[in] order desired order of the Legendre polynomial
Returns
Legendre polynomial of order order
Definition at line 106 of file polynomial_impl.hpp.
Referenced by pfasst::quadrature::GaussLegendre< precision >::compute_nodes(), pfasst::quadrature::GaussRadau< precision >::compute_nodes(), pfasst::quadrature::GaussLobatto< precision >::compute_nodes(), pfasst::quadrature::ClenshawCurtis< precision >::compute_nodes(), and TEST().
template<typename CoeffT > Polynomial< CoeffT > pfasst::quadrature::Polynomial< CoeffT >::normalize () const
Normalizes this polynomial with respect to \(c_0 \).
Returns
normalized polynomial
Definition at line 55 of file polynomial_impl.hpp.
template<typename CoeffT > CoeffT & pfasst::quadrature::Polynomial< CoeffT >::operator[] (const size_t i)
Access coefficient i.
Parameters
[in] i coefficient index (zero-based)
Returns
\(i+1 \)-th coefficient
Exceptions
std::out_of_range if index is out of bounds, i.e. i >= Polynomial::order()
Note
The coefficients are stored in reversed order to the degree of the indeterminate, i.e. i=0 corresponds to \(c_n \) while i=n corresponds to \(c_0 \). See also Polynomial::c.
Definition at line 29 of file polynomial_impl.hpp.
template<typename CoeffT > size_t pfasst::quadrature::Polynomial< CoeffT >::order () const
Order of this polynomial.
The order of this polynomial is one less the number of coefficients defined.
Returns
order of the polynomial
Definition at line 23 of file polynomial_impl.hpp.
template<typename CoeffT > vector< CoeffT > pfasst::quadrature::Polynomial< CoeffT >::roots (size_t num_iterations = 100, CoeffT ztol = 1.0e-20) const
Computes the roots of this polynomial.
Returns
roots sorted with respect to their value
Definition at line 70 of file polynomial_impl.hpp.
References pfasst::quadrature::Polynomial< CoeffT >::evaluate().
Member Data Documentation
template<typename CoeffT> vector<CoeffT> pfasst::quadrature::Polynomial< CoeffT >::c protected
Coefficients of the polynomial.
The coefficient for the highest degree of \(x \) has index 0. The last coefficient is for \(x^0 \).
Definition at line 37 of file polynomial.hpp.
The documentation for this class was generated from the following files:
include/pfasst/quadrature/polynomial.hpp
src/pfasst/quadrature/polynomial_impl.hpp