PFASST++: pfasst::ICommunicator Class Reference
pfasst::ICommunicator Class Reference abstract
Abstract interface for communicators.
#include <interfaces.hpp>
Public Member Functions
virtual ~ICommunicator ()
virtual int size ()=0
virtual int rank ()=0
Public Attributes
shared_ptr< IStatus > status
Detailed Description
Abstract interface for communicators.
The interface ensures a communicator provides the notion of the total number of processors (i.e. size()) and and the ID of the current processor (i.e. rank()) as well as the current status of the algorithm.
Definition at line 70 of file interfaces.hpp.
Constructor & Destructor Documentation
pfasst::ICommunicator::~ICommunicator () virtual
Definition at line 44 of file interfaces_impl.hpp.
Member Function Documentation
virtual int pfasst::ICommunicator::rank () pure virtual
Implemented in pfasst::mpi::MPICommunicator.
Referenced by pfasst::encap::EncapSweeper< time >::broadcast(), pfasst::examples::boris::BorisSweeper< scalar, time >::broadcast(), pfasst::IStatus::keep_iterating(), pfasst::IStatus::previous_is_iterating(), and pfasst::mpi::MPIStatus::set_converged().
virtual int pfasst::ICommunicator::size () pure virtual
Implemented in pfasst::mpi::MPICommunicator.
Referenced by pfasst::encap::EncapSweeper< time >::broadcast(), pfasst::examples::boris::BorisSweeper< scalar, time >::broadcast(), and pfasst::mpi::MPIStatus::set_comm().
Member Data Documentation
shared_ptr<IStatus> pfasst::ICommunicator::status
Definition at line 77 of file interfaces.hpp.
Referenced by pfasst::mpi::MPICommunicator::set_comm().
The documentation for this class was generated from the following files:
include/pfasst/interfaces.hpp
src/pfasst/interfaces_impl.hpp