PFASST++: pfasst::examples::advection_diffusion::SpectralTransfer1D< time > Class Template Reference
pfasst::examples::advection_diffusion::SpectralTransfer1D< time > Class Template Reference
Examples » Advection Diffusion
Spectral (FFT) transfer routines.
#include <spectral_transfer_1d.hpp>
Public Member Functions
void interpolate (shared_ptr< Encapsulation > dst, shared_ptr< const Encapsulation > src) override
void restrict (shared_ptr< Encapsulation > dst, shared_ptr< const Encapsulation > src) override
Public Member Functions inherited from pfasst::encap::PolyInterpMixin< time >
virtual ~PolyInterpMixin ()
virtual void interpolate_initial (shared_ptr< ISweeper< time >> dst, shared_ptr< const ISweeper< time >> src) override
Interpolate initial condition from the coarse sweeper to the fine sweeper.
virtual void interpolate (shared_ptr< ISweeper< time >> dst, shared_ptr< const ISweeper< time >> src, bool interp_initial) override
Interpolate, in time and space, from the coarse sweeper to the fine sweeper.
virtual void interpolate (shared_ptr< Encapsulation< time >> dst, shared_ptr< const Encapsulation< time >> src)
virtual void restrict_initial (shared_ptr< ISweeper< time >> dst, shared_ptr< const ISweeper< time >> src) override
Restrict initial condition from the fine sweeper to the coarse sweeper.
virtual void restrict (shared_ptr< ISweeper< time >> dst, shared_ptr< const ISweeper< time >> src, bool restrict_initial) override
Restrict, in time and space, from the fine sweeper to the coarse sweeper.
virtual void restrict (shared_ptr< Encapsulation< time >> dst, shared_ptr< const Encapsulation< time >> src)
virtual void fas (time dt, shared_ptr< ISweeper< time >> dst, shared_ptr< const ISweeper< time >> src) override
Compute FAS correction between the coarse and fine sweepers.
Public Member Functions inherited from pfasst::ITransfer< time >
virtual ~ITransfer ()
Private Types
typedef encap::Encapsulation< double > Encapsulation
Private Attributes
FFT fft
Additional Inherited Members
Protected Types inherited from pfasst::encap::PolyInterpMixin< time >
typedef vector< shared_ptr< Encapsulation< time > > > EncapVecT
Protected Attributes inherited from pfasst::encap::PolyInterpMixin< time >
Matrix< time > tmat
Matrix< time > fmat
Detailed Description
template<typename time = pfasst::time_precision>
class pfasst::examples::advection_diffusion::SpectralTransfer1D< time >
Spectral (FFT) transfer routines.
Definition at line 32 of file spectral_transfer_1d.hpp.
Member Typedef Documentation
template<typename time = pfasst::time_precision> typedef encap::Encapsulation<double> pfasst::examples::advection_diffusion::SpectralTransfer1D< time >::Encapsulation private
Definition at line 35 of file spectral_transfer_1d.hpp.
Member Function Documentation
template<typename time = pfasst::time_precision> void pfasst::examples::advection_diffusion::SpectralTransfer1D< time >::interpolate (shared_ptr< Encapsulation > dst, shared_ptr< const Encapsulation > src) inline override
Definition at line 40 of file spectral_transfer_1d.hpp.
References pfasst::examples::advection_diffusion::FFT::backward(), pfasst::examples::advection_diffusion::FFT::forward(), and pfasst::examples::advection_diffusion::FFT::get_workspace().
template<typename time = pfasst::time_precision> void pfasst::examples::advection_diffusion::SpectralTransfer1D< time >::restrict (shared_ptr< Encapsulation > dst, shared_ptr< const Encapsulation > src) inline override
Definition at line 65 of file spectral_transfer_1d.hpp.
Member Data Documentation
template<typename time = pfasst::time_precision> FFT pfasst::examples::advection_diffusion::SpectralTransfer1D< time >::fft private
Definition at line 37 of file spectral_transfer_1d.hpp.
The documentation for this class was generated from the following file:
examples/advection_diffusion/spectral_transfer_1d.hpp