PFASST++: pfasst::examples::boris::Particle< precision > Class Template Reference
pfasst::examples::boris::Particle< precision > Class Template Reference
Examples » Boris
#include <particle.hpp>
Public Member Functions
Particle (const size_t dim=3)
Particle (const size_t dim, const precision charge, const precision mass)
virtual ~Particle ()
size_t dim () const
ParticleComponent< precision > & pos ()
const ParticleComponent< precision > & pos () const
ParticleComponent< precision > & vel ()
const ParticleComponent< precision > & vel () const
const precision charge () const
const precision mass () const
const precision alpha () const
void set_charge (const precision &charge)
void set_mass (const precision &mass)
virtual void log (el::base::type::ostream_t &os) const
Protected Attributes
size_t _dim
precision _charge
precision _mass
ParticleComponent< precision > _pos
ParticleComponent< precision > _vel
Detailed Description
template<typename precision>
class pfasst::examples::boris::Particle< precision >
Definition at line 42 of file particle.hpp.
Constructor & Destructor Documentation
template<typename precision > pfasst::examples::boris::Particle< precision >::Particle (const size_t dim = 3) explicit
Definition at line 27 of file particle_impl.hpp.
template<typename precision > pfasst::examples::boris::Particle< precision >::Particle (const size_t dim, const precision charge, const precision mass)
Definition at line 32 of file particle_impl.hpp.
References pfasst::examples::boris::Particle< precision >::_pos, pfasst::examples::boris::Particle< precision >::_vel, and pfasst::examples::boris::Particle< precision >::dim().
template<typename precision > pfasst::examples::boris::Particle< precision >::~Particle () virtual
Definition at line 44 of file particle_impl.hpp.
Member Function Documentation
template<typename precision > const precision pfasst::examples::boris::Particle< precision >::alpha () const
Definition at line 88 of file particle_impl.hpp.
template<typename precision > const precision pfasst::examples::boris::Particle< precision >::charge () const
Definition at line 76 of file particle_impl.hpp.
template<typename precision > size_t pfasst::examples::boris::Particle< precision >::dim () const inline
Definition at line 48 of file particle_impl.hpp.
Referenced by pfasst::examples::boris::distance(), and pfasst::examples::boris::Particle< precision >::Particle().
template<typename precision > void pfasst::examples::boris::Particle< precision >::log (el::base::type::ostream_t & os) const virtual
Definition at line 106 of file particle_impl.hpp.
References LOG_PRECISION.
template<typename precision > const precision pfasst::examples::boris::Particle< precision >::mass () const
Definition at line 82 of file particle_impl.hpp.
template<typename precision > ParticleComponent< precision > & pfasst::examples::boris::Particle< precision >::pos ()
Definition at line 59 of file particle_impl.hpp.
Referenced by pfasst::examples::boris::distance(), and TEST().
template<typename precision > const ParticleComponent< precision > & pfasst::examples::boris::Particle< precision >::pos () const
Definition at line 54 of file particle_impl.hpp.
template<typename precision > void pfasst::examples::boris::Particle< precision >::set_charge (const precision & charge)
Definition at line 94 of file particle_impl.hpp.
template<typename precision > void pfasst::examples::boris::Particle< precision >::set_mass (const precision & mass)
Definition at line 100 of file particle_impl.hpp.
template<typename precision > ParticleComponent< precision > & pfasst::examples::boris::Particle< precision >::vel ()
Definition at line 70 of file particle_impl.hpp.
template<typename precision > const ParticleComponent< precision > & pfasst::examples::boris::Particle< precision >::vel () const
Definition at line 65 of file particle_impl.hpp.
Member Data Documentation
template<typename precision> precision pfasst::examples::boris::Particle< precision >::_charge protected
Definition at line 47 of file particle.hpp.
template<typename precision> size_t pfasst::examples::boris::Particle< precision >::_dim protected
Definition at line 46 of file particle.hpp.
template<typename precision> precision pfasst::examples::boris::Particle< precision >::_mass protected
Definition at line 48 of file particle.hpp.
template<typename precision> ParticleComponent<precision> pfasst::examples::boris::Particle< precision >::_pos protected
Definition at line 49 of file particle.hpp.
Referenced by pfasst::examples::boris::Particle< precision >::Particle().
template<typename precision> ParticleComponent<precision> pfasst::examples::boris::Particle< precision >::_vel protected
Definition at line 50 of file particle.hpp.
Referenced by pfasst::examples::boris::Particle< precision >::Particle().
The documentation for this class was generated from the following files:
examples/boris/particle.hpp
examples/boris/particle_impl.hpp