PFASST++: Scalar
Scalar
Examples
This directory contains a simple implementations of scalar ODE solver using the PFASST framework.
Modules
Files
This directory contains a simple implementations of scalar ODE solver using the PFASST framework.
Classes
class pfasst::examples::scalar::ScalarSweeper< time >
Sweeper for scalar test equation.
Functions
double pfasst::examples::scalar::run_scalar_sdc (const size_t nsteps, const double dt, const size_t nnodes, const size_t niters, const complex< double > lambda, const quadrature::QuadratureType nodetype)
Scalar test equation example using an encapsulated IMEX sweeper.
Detailed Description
This directory contains a simple implementations of scalar ODE solver using the PFASST framework.
The SDC sweeper is defined in scalar_sweeper.hpp. As this simple equation does not require any special handling, all the SDC magic is derived and taken from pfasst::encap::IMEXSweeper::sweep().
Function Documentation
double pfasst::examples::scalar::run_scalar_sdc (const size_t nsteps, const double dt, const size_t nnodes, const size_t niters, const complex< double > lambda, const quadrature::QuadratureType nodetype)
Scalar test equation example using an encapsulated IMEX sweeper.
Solves Dahlquist's test equation with single level SDC
\(u' = \lambda*u \quad\text{ , } u(0) = u_0 \)
with complex lambda, treating the real part implicitly and the imaginary part explicitly.
Definition at line 38 of file scalar_sdc.cpp.
References pfasst::Controller< time >::add_level(), pfasst::quadrature::quadrature_factory(), pfasst::SDC< time >::run(), pfasst::Controller< time >::set_duration(), and pfasst::Controller< time >::setup().
Referenced by main(), ConvergenceTest::SetUp(), and HighPrecisionTest::SetUp().