PFASST++: pfasst::examples::boris::bindings::WrapperSimplePhysicsSolver< scalar, time > Class Template Reference
pfasst::examples::boris::bindings::WrapperSimplePhysicsSolver< scalar, time > Class Template Reference
#include <wrapper_simple_physics_solver.hpp>
Public Types
typedef shared_ptr< ParticleCloud< scalar > > particle_cloud_type
Public Types inherited from pfasst::examples::boris::bindings::WrapperInterface< scalar, time >
typedef shared_ptr< ParticleCloud< scalar > > particle_cloud_type
Public Member Functions
WrapperSimplePhysicsSolver ()
virtual ~WrapperSimplePhysicsSolver ()
virtual ParticleCloudComponent< scalar > external_e_field_evaluate (const particle_cloud_type &particles, const time t) override
virtual ParticleCloudComponent< scalar > e_field_evaluate (const particle_cloud_type &particles, const time t) override
virtual ParticleCloudComponent< scalar > b_field_evaluate (const particle_cloud_type &particles, const time t) override
virtual ParticleCloudComponent< scalar > force_evaluate (const particle_cloud_type &particles, const time t) override
virtual scalar energy (const particle_cloud_type &particles, const time t) override
virtual ParticleComponent< scalar > get_b_field_vector () override
virtual ParticleCloudComponent< scalar > b_field_vecs (const particle_cloud_type &particles, const time t) override
virtual void set_config (shared_ptr< solver::SimplePhysicsSolverConfig > config)
virtual scalar omega_b () const
virtual scalar omega_e () const
virtual scalar epsilon () const
virtual void log (el::base::type::ostream_t &os) const
Public Member Functions inherited from pfasst::examples::boris::bindings::WrapperInterface< scalar, time >
virtual ~WrapperInterface ()
Protected Member Functions
virtual size_t vector_to_array (const vector< scalar > &vec, scalar *arr)
virtual size_t vector2d_to_array (const vector< scalar > &vec, scalar *arr)
virtual size_t pack_positions (const particle_cloud_type &particles, scalar *packed) override
virtual size_t pack_velocities (const particle_cloud_type &particles, scalar *packed) override
virtual size_t pack_charges (const particle_cloud_type &particles, scalar *packed) override
virtual size_t pack_masses (const particle_cloud_type &particles, scalar *packed) override
virtual size_t pack_all (const particle_cloud_type &particles, scalar *packed_positions, scalar *packed_velocities, scalar *packed_charges, scalar *packed_masses) override
virtual vector< scalar > unpack_1d (const scalar *packed, const size_t num_particles)
virtual ParticleCloudComponent< scalar > unpack_2d (const scalar *packed, const size_t num_particles)
Private Attributes
shared_ptr< solver::SimplePhysicsSolverConfig > config
Detailed Description
template<typename scalar, typename time>
class pfasst::examples::boris::bindings::WrapperSimplePhysicsSolver< scalar, time >
Definition at line 34 of file wrapper_simple_physics_solver.hpp.
Member Typedef Documentation
template<typename scalar , typename time > typedef shared_ptr<ParticleCloud<scalar> > pfasst::examples::boris::bindings::WrapperSimplePhysicsSolver< scalar, time >::particle_cloud_type
Definition at line 41 of file wrapper_simple_physics_solver.hpp.
Constructor & Destructor Documentation
template<typename scalar , typename time > pfasst::examples::boris::bindings::WrapperSimplePhysicsSolver< scalar, time >::WrapperSimplePhysicsSolver ()
Definition at line 103 of file wrapper_simple_physics_solver_impl.hpp.
template<typename scalar , typename time > pfasst::examples::boris::bindings::WrapperSimplePhysicsSolver< scalar, time >::~WrapperSimplePhysicsSolver () virtual
Definition at line 107 of file wrapper_simple_physics_solver_impl.hpp.
Member Function Documentation
template<typename scalar , typename time > ParticleCloudComponent< scalar > pfasst::examples::boris::bindings::WrapperSimplePhysicsSolver< scalar, time >::b_field_evaluate (const particle_cloud_type & particles, const time t) override virtual
Implements pfasst::examples::boris::bindings::WrapperInterface< scalar, time >.
Definition at line 166 of file wrapper_simple_physics_solver_impl.hpp.
References DIM, simple_physics_solver::evaluate_b_field(), and ML_CVLOG.
template<typename scalar , typename time > ParticleCloudComponent< scalar > pfasst::examples::boris::bindings::WrapperSimplePhysicsSolver< scalar, time >::b_field_vecs (const particle_cloud_type & particles, const time t) override virtual
Implements pfasst::examples::boris::bindings::WrapperInterface< scalar, time >.
Definition at line 193 of file wrapper_simple_physics_solver_impl.hpp.
References DIM, and simple_physics_solver::get_b_field_vector().
template<typename scalar , typename time > ParticleCloudComponent< scalar > pfasst::examples::boris::bindings::WrapperSimplePhysicsSolver< scalar, time >::e_field_evaluate (const particle_cloud_type & particles, const time t) override virtual
Implements pfasst::examples::boris::bindings::WrapperInterface< scalar, time >.
Definition at line 139 of file wrapper_simple_physics_solver_impl.hpp.
References DIM, simple_physics_solver::evaluate_e_field(), and ML_CVLOG.
template<typename scalar , typename time > scalar pfasst::examples::boris::bindings::WrapperSimplePhysicsSolver< scalar, time >::energy (const particle_cloud_type & particles, const time t) override virtual
Implements pfasst::examples::boris::bindings::WrapperInterface< scalar, time >.
Definition at line 215 of file wrapper_simple_physics_solver_impl.hpp.
References simple_physics_solver::compute_energy(), DIM, and ML_CVLOG.
template<typename scalar , typename time > scalar pfasst::examples::boris::bindings::WrapperSimplePhysicsSolver< scalar, time >::epsilon () const virtual
Implements pfasst::examples::boris::bindings::WrapperInterface< scalar, time >.
Definition at line 272 of file wrapper_simple_physics_solver_impl.hpp.
template<typename scalar , typename time > ParticleCloudComponent< scalar > pfasst::examples::boris::bindings::WrapperSimplePhysicsSolver< scalar, time >::external_e_field_evaluate (const particle_cloud_type & particles, const time t) override virtual
Implements pfasst::examples::boris::bindings::WrapperInterface< scalar, time >.
Definition at line 112 of file wrapper_simple_physics_solver_impl.hpp.
References DIM, simple_physics_solver::evaluate_external_e_field(), and ML_CVLOG.
template<typename scalar , typename time > ParticleCloudComponent< scalar > pfasst::examples::boris::bindings::WrapperSimplePhysicsSolver< scalar, time >::force_evaluate (const particle_cloud_type & particles, const time t) override virtual
Implements pfasst::examples::boris::bindings::WrapperInterface< scalar, time >.
Definition at line 205 of file wrapper_simple_physics_solver_impl.hpp.
References ML_CVLOG.
template<typename scalar , typename time > ParticleComponent< scalar > pfasst::examples::boris::bindings::WrapperSimplePhysicsSolver< scalar, time >::get_b_field_vector () override virtual
Implements pfasst::examples::boris::bindings::WrapperInterface< scalar, time >.
Definition at line 240 of file wrapper_simple_physics_solver_impl.hpp.
References DIM, and simple_physics_solver::get_b_field_vector().
template<typename precision , typename time > void pfasst::examples::boris::bindings::WrapperSimplePhysicsSolver< precision, time >::log (el::base::type::ostream_t & os) const virtual
Implements pfasst::examples::boris::bindings::WrapperInterface< scalar, time >.
Definition at line 278 of file wrapper_simple_physics_solver_impl.hpp.
template<typename scalar , typename time > scalar pfasst::examples::boris::bindings::WrapperSimplePhysicsSolver< scalar, time >::omega_b () const virtual
Implements pfasst::examples::boris::bindings::WrapperInterface< scalar, time >.
Definition at line 265 of file wrapper_simple_physics_solver_impl.hpp.
template<typename scalar , typename time > scalar pfasst::examples::boris::bindings::WrapperSimplePhysicsSolver< scalar, time >::omega_e () const virtual
Implements pfasst::examples::boris::bindings::WrapperInterface< scalar, time >.
Definition at line 258 of file wrapper_simple_physics_solver_impl.hpp.
template<typename scalar , typename time > size_t pfasst::examples::boris::bindings::WrapperSimplePhysicsSolver< scalar, time >::pack_all (const particle_cloud_type & particles, scalar * packed_positions, scalar * packed_velocities, scalar * packed_charges, scalar * packed_masses) override protected virtual
Implements pfasst::examples::boris::bindings::WrapperInterface< scalar, time >.
Definition at line 71 of file wrapper_simple_physics_solver_impl.hpp.
template<typename scalar , typename time > size_t pfasst::examples::boris::bindings::WrapperSimplePhysicsSolver< scalar, time >::pack_charges (const particle_cloud_type & particles, scalar * packed) override protected virtual
Implements pfasst::examples::boris::bindings::WrapperInterface< scalar, time >.
Definition at line 57 of file wrapper_simple_physics_solver_impl.hpp.
template<typename scalar , typename time > size_t pfasst::examples::boris::bindings::WrapperSimplePhysicsSolver< scalar, time >::pack_masses (const particle_cloud_type & particles, scalar * packed) override protected virtual
Implements pfasst::examples::boris::bindings::WrapperInterface< scalar, time >.
Definition at line 64 of file wrapper_simple_physics_solver_impl.hpp.
template<typename scalar , typename time > size_t pfasst::examples::boris::bindings::WrapperSimplePhysicsSolver< scalar, time >::pack_positions (const particle_cloud_type & particles, scalar * packed) override protected virtual
Implements pfasst::examples::boris::bindings::WrapperInterface< scalar, time >.
Definition at line 43 of file wrapper_simple_physics_solver_impl.hpp.
template<typename scalar , typename time > size_t pfasst::examples::boris::bindings::WrapperSimplePhysicsSolver< scalar, time >::pack_velocities (const particle_cloud_type & particles, scalar * packed) override protected virtual
Implements pfasst::examples::boris::bindings::WrapperInterface< scalar, time >.
Definition at line 50 of file wrapper_simple_physics_solver_impl.hpp.
template<typename scalar , typename time > void pfasst::examples::boris::bindings::WrapperSimplePhysicsSolver< scalar, time >::set_config (shared_ptr< solver::SimplePhysicsSolverConfig > config) virtual
Definition at line 251 of file wrapper_simple_physics_solver_impl.hpp.
template<typename scalar , typename time > vector< scalar > pfasst::examples::boris::bindings::WrapperSimplePhysicsSolver< scalar, time >::unpack_1d (const scalar * packed, const size_t num_particles) protected virtual
Definition at line 84 of file wrapper_simple_physics_solver_impl.hpp.
template<typename scalar , typename time > ParticleCloudComponent< scalar > pfasst::examples::boris::bindings::WrapperSimplePhysicsSolver< scalar, time >::unpack_2d (const scalar * packed, const size_t num_particles) protected virtual
Definition at line 95 of file wrapper_simple_physics_solver_impl.hpp.
References DIM.
template<typename scalar , typename time > size_t pfasst::examples::boris::bindings::WrapperSimplePhysicsSolver< scalar, time >::vector2d_to_array (const vector< scalar > & vec, scalar * arr) protected virtual
Definition at line 30 of file wrapper_simple_physics_solver_impl.hpp.
References DIM.
template<typename scalar , typename time > size_t pfasst::examples::boris::bindings::WrapperSimplePhysicsSolver< scalar, time >::vector_to_array (const vector< scalar > & vec, scalar * arr) protected virtual
Definition at line 20 of file wrapper_simple_physics_solver_impl.hpp.
Member Data Documentation
template<typename scalar , typename time > shared_ptr<solver::SimplePhysicsSolverConfig> pfasst::examples::boris::bindings::WrapperSimplePhysicsSolver< scalar, time >::config private
Definition at line 38 of file wrapper_simple_physics_solver.hpp.
The documentation for this class was generated from the following files:
examples/boris/bindings/wrapper_simple_physics_solver.hpp
examples/boris/bindings/wrapper_simple_physics_solver_impl.hpp