PFASST++: Bindings
Bindings
Examples » Boris
Modules
External Solver
Namespaces
pfasst::examples::boris::bindings
Classes
class pfasst::examples::boris::bindings::WrapperInterface< scalar, time >
Functions
template<typename scalar , typename time >
void pfasst::examples::boris::bindings::setup (shared_ptr< WrapperInterface< scalar, time >> wrapper)
template<typename scalar , typename time , typename ArgT >
void pfasst::examples::boris::bindings::setup (shared_ptr< WrapperInterface< scalar, time >> wrapper, ArgT arg)
template<typename scalar , typename time , typename ArgT , typename... ArgsT>
void pfasst::examples::boris::bindings::setup (shared_ptr< WrapperInterface< scalar, time >> wrapper, ArgT arg, ArgsT...args)
Detailed Description
Function Documentation
template<typename scalar , typename time > void pfasst::examples::boris::bindings::setup (shared_ptr< WrapperInterface< scalar, time >> wrapper)
Definition at line 84 of file wrapper_interface.hpp.
References UNUSED.
Referenced by pfasst::examples::boris::run_boris_pfasst(), pfasst::examples::boris::run_boris_sdc(), and pfasst::examples::boris::bindings::setup().
template<typename scalar , typename time , typename ArgT > void pfasst::examples::boris::bindings::setup (shared_ptr< WrapperInterface< scalar, time >> wrapper, ArgT arg)
Definition at line 91 of file wrapper_interface.hpp.
References UNUSED.
template<typename scalar , typename time , typename ArgT , typename... ArgsT> void pfasst::examples::boris::bindings::setup (shared_ptr< WrapperInterface< scalar, time >> wrapper, ArgT arg, ArgsT... args)
Definition at line 98 of file wrapper_interface.hpp.