PFASST++: pfasst::mpi::MPICommunicator Class Reference
pfasst::mpi::MPICommunicator Class Reference
#include <mpi_communicator.hpp>
Public Member Functions
MPICommunicator ()
MPICommunicator (MPI_Comm comm)
virtual void set_comm (MPI_Comm comm)
virtual int size ()
virtual int rank ()
virtual string name ()
Public Member Functions inherited from pfasst::ICommunicator
virtual ~ICommunicator ()
Public Attributes
MPI_Comm comm
Public Attributes inherited from pfasst::ICommunicator
shared_ptr< IStatus > status
Private Attributes
int _rank
int _size
string _name
Detailed Description
Definition at line 76 of file mpi_communicator.hpp.
Constructor & Destructor Documentation
pfasst::mpi::MPICommunicator::MPICommunicator ()
Definition at line 29 of file mpi_communicator_impl.hpp.
pfasst::mpi::MPICommunicator::MPICommunicator (MPI_Comm comm)
Definition at line 32 of file mpi_communicator_impl.hpp.
References set_comm().
Member Function Documentation
string pfasst::mpi::MPICommunicator::name () virtual
Definition at line 67 of file mpi_communicator_impl.hpp.
References _name.
int pfasst::mpi::MPICommunicator::rank () virtual
Implements pfasst::ICommunicator.
Definition at line 62 of file mpi_communicator_impl.hpp.
References _rank.
Referenced by pfasst::mpi::MPIStatus::recv(), and pfasst::mpi::MPIStatus::send().
void pfasst::mpi::MPICommunicator::set_comm (MPI_Comm comm) virtual
Definition at line 37 of file mpi_communicator_impl.hpp.
References _name, _rank, _size, pfasst::mpi::check_mpi_error(), comm, and pfasst::ICommunicator::status.
Referenced by MPICommunicator().
int pfasst::mpi::MPICommunicator::size () virtual
Implements pfasst::ICommunicator.
Definition at line 57 of file mpi_communicator_impl.hpp.
References _size.
Referenced by pfasst::mpi::MPIStatus::recv(), and pfasst::mpi::MPIStatus::send().
Member Data Documentation
string pfasst::mpi::MPICommunicator::_name private
Definition at line 82 of file mpi_communicator.hpp.
Referenced by name(), and set_comm().
int pfasst::mpi::MPICommunicator::_rank private
Definition at line 80 of file mpi_communicator.hpp.
Referenced by rank(), and set_comm().
int pfasst::mpi::MPICommunicator::_size private
Definition at line 81 of file mpi_communicator.hpp.
Referenced by set_comm(), and size().
MPI_Comm pfasst::mpi::MPICommunicator::comm
Definition at line 87 of file mpi_communicator.hpp.
Referenced by pfasst::mpi::MPIStatus::recv(), pfasst::mpi::MPIStatus::send(), and set_comm().
The documentation for this class was generated from the following files:
include/pfasst/mpi_communicator.hpp
src/pfasst/mpi_communicator_impl.hpp