PFASST++: pfasst::mpi::MPIStatus Class Reference
pfasst::mpi::MPIStatus Class Reference
#include <mpi_communicator.hpp>
Public Member Functions
virtual void set_comm (ICommunicator *comm)
Set new communicator to use.
virtual void clear () override
Resetting status.
virtual void set_converged (bool converged) override
sets a new converged state.
virtual bool get_converged (int rank) override
Retreive converged state for specific processor.
virtual void post (int tag) override
virtual void send (int tag) override
virtual void recv (int tag) override
Public Member Functions inherited from pfasst::IStatus
virtual ~IStatus ()
virtual bool previous_is_iterating ()
Check whether previous processor is still iterating.
virtual bool keep_iterating ()
Check whether this processor should keep iterating.
Protected Attributes
vector< bool > converged
MPICommunicator * mpi
Protected Attributes inherited from pfasst::IStatus
ICommunicator * comm
Additional Inherited Members
Static Public Attributes inherited from pfasst::IStatus
static const int NOT_CONVERGED = 0
static const int CONVERGED = 1
Detailed Description
Definition at line 104 of file mpi_communicator.hpp.
Member Function Documentation
void pfasst::mpi::MPIStatus::clear () override virtual
Resetting status.
Note
Logic is implementation defined.
Implements pfasst::IStatus.
Definition at line 81 of file mpi_communicator_impl.hpp.
References converged.
bool pfasst::mpi::MPIStatus::get_converged (int rank) override virtual
Retreive converged state for specific processor.
Parameters
[in] rank ID of processor to check converged state for
Returns
true if processor with ID rank has converged; false otherwise
Note
Inspection logic is implementation defined.
Implements pfasst::IStatus.
Definition at line 94 of file mpi_communicator_impl.hpp.
References converged.
Referenced by recv().
void pfasst::mpi::MPIStatus::post (int tag) override virtual
Implements pfasst::IStatus.
Definition at line 99 of file mpi_communicator_impl.hpp.
References UNUSED.
void pfasst::mpi::MPIStatus::recv (int tag) override virtual
Implements pfasst::IStatus.
Definition at line 122 of file mpi_communicator_impl.hpp.
References pfasst::mpi::check_mpi_error(), pfasst::mpi::MPICommunicator::comm, pfasst::IStatus::CONVERGED, converged, get_converged(), ML_CLOG, mpi, MPI_Status_factory(), pfasst::IStatus::NOT_CONVERGED, pfasst::mpi::MPICommunicator::rank(), and pfasst::mpi::MPICommunicator::size().
void pfasst::mpi::MPIStatus::send (int tag) override virtual
Implements pfasst::IStatus.
Definition at line 105 of file mpi_communicator_impl.hpp.
References pfasst::mpi::check_mpi_error(), pfasst::mpi::MPICommunicator::comm, pfasst::IStatus::CONVERGED, converged, ML_CLOG, mpi, pfasst::IStatus::NOT_CONVERGED, pfasst::mpi::MPICommunicator::rank(), and pfasst::mpi::MPICommunicator::size().
void pfasst::mpi::MPIStatus::set_comm (ICommunicator * comm) virtual
Set new communicator to use.
Todo:
Consider asserting validity of the given pointer to the communicator.
Reimplemented from pfasst::IStatus.
Definition at line 73 of file mpi_communicator_impl.hpp.
References pfasst::IStatus::comm, converged, mpi, and pfasst::ICommunicator::size().
void pfasst::mpi::MPIStatus::set_converged (bool converged) override virtual
sets a new converged state.
Implements pfasst::IStatus.
Definition at line 86 of file mpi_communicator_impl.hpp.
References pfasst::IStatus::comm, ML_CLOG, and pfasst::ICommunicator::rank().
Member Data Documentation
vector<bool> pfasst::mpi::MPIStatus::converged protected
Definition at line 108 of file mpi_communicator.hpp.
Referenced by clear(), get_converged(), recv(), send(), and set_comm().
MPICommunicator* pfasst::mpi::MPIStatus::mpi protected
Definition at line 109 of file mpi_communicator.hpp.
Referenced by recv(), send(), and set_comm().
The documentation for this class was generated from the following files:
include/pfasst/mpi_communicator.hpp
src/pfasst/mpi_communicator_impl.hpp