PFASST++: tests/examples/advection_diffusion/test_advection_diffusion.cpp File Reference
test_advection_diffusion.cpp File Reference
#include <algorithm>
#include <iostream>
#include <tuple>
#include <vector>
#include <gtest/gtest.h>
#include <gmock/gmock.h>
#include "../examples/advection_diffusion/vanilla_sdc.cpp"
#include "../examples/advection_diffusion/serial_mlsdc.cpp"
Macros
#define PFASST_UNIT_TESTING
Functions
MATCHER (DoubleNear,"")
MATCHER (DoubleLess,"")
TEST (ErrorTest, VanillaSDC)
TEST (AdaptiveErrorTest, VanillaSDC)
TEST (RelativeAdaptiveErrorTest, VanillaSDC)
TEST (ErrorTest, SerialMLSDC)
TEST (FASTest, SerialMLSDC)
int main (int argc, char **argv)
Macro Definition Documentation
#define PFASST_UNIT_TESTING
Definition at line 14 of file test_advection_diffusion.cpp.
Function Documentation
int main (int argc, char ** argv)
Definition at line 157 of file test_advection_diffusion.cpp.
References pfasst::log::add_custom_logger(), and pfasst::log::start_log().
MATCHER (DoubleNear , "")
Definition at line 21 of file test_advection_diffusion.cpp.
MATCHER (DoubleLess , "")
Definition at line 26 of file test_advection_diffusion.cpp.
TEST (ErrorTest , VanillaSDC)
Definition at line 31 of file test_advection_diffusion.cpp.
References pfasst::examples::advection_diffusion::run_vanilla_sdc().
TEST (AdaptiveErrorTest , VanillaSDC)
Definition at line 54 of file test_advection_diffusion.cpp.
References pfasst::examples::advection_diffusion::run_vanilla_sdc().
TEST (RelativeAdaptiveErrorTest , VanillaSDC)
Definition at line 77 of file test_advection_diffusion.cpp.
References pfasst::examples::advection_diffusion::run_vanilla_sdc().
TEST (ErrorTest , SerialMLSDC)
Definition at line 100 of file test_advection_diffusion.cpp.
References pfasst::examples::advection_diffusion::run_serial_mlsdc().
TEST (FASTest , SerialMLSDC)
Definition at line 123 of file test_advection_diffusion.cpp.
References pfasst::examples::advection_diffusion::run_serial_mlsdc().