PFASST++: tests/examples/boris/test_boris_particle_util.cpp File Reference
test_boris_particle_util.cpp File Reference
#include <memory>
#include <random>
#include <type_traits>
#include <gtest/gtest.h>
#include <gmock/gmock.h>
#include "../examples/boris/particle.hpp"
#include "../examples/boris/particle_cloud.hpp"
#include "../examples/boris/particle_util.hpp"
Classes
struct RandomGenerator
Macros
#define DIMS 3
#define PRECISION double
#define create_single(name, num) ParticleComponent<PRECISION> name(num)
#define create_and_fill_single(name, num)
#define create_cloud(name, num) create_single(name, num * DIMS)
#define create_and_fill_cloud(name, num) create_and_fill_single(name, num * DIMS)
Functions
void fill_single (ParticleComponent< PRECISION > &vec)
TEST (OperatorTests, AddSingleOnSingle)
TEST (OperatorTests, AddCloudOnCloud)
TEST (OperatorTests, AddSingleOnCloud)
TEST (OperatorTests, InplaceAddSingleOnSingle)
TEST (OperatorTests, InplaceAddCloudOnCloud)
TEST (OperatorTests, InplaceAddSingleOnCloud)
TEST (OperatorTests, MinusSingleOnSingle)
TEST (OperatorTests, MinusCloudOnCloud)
TEST (OperatorTests, MinusSingleOnCloud)
TEST (OperatorTests, InplaceMinusSingleOnSingle)
TEST (OperatorTests, InplaceMinusCloudOnCloud)
TEST (OperatorTests, InplaceMinusSingleOnCloud)
TEST (OperatorTests, MulWithSingle)
TEST (OperatorTests, MulWithCloud)
TEST (OperatorTests, InplaceMulWithSingle)
TEST (OperatorTests, InplaceMulWithCloud)
TEST (OperatorTests, DivWithSingle)
TEST (OperatorTests, DivWithCloud)
TEST (OperatorTests, InplaceDivWithSingle)
TEST (OperatorTests, InplaceDivWithCloud)
TEST (OperatorTests, CrossProdSingleOnSingle)
TEST (OperatorTests, CrossProdCloudOnCloud)
TEST (OperatorTests, CrossProdSingleOnCloud)
TEST (UtilitiesTests, DistanceBetweenTwoParticles)
TEST (UtilitiesTests, DistanceOfCloudToReference)
int main (int argc, char **argv)
Macro Definition Documentation
#define create_and_fill_cloud (name, num) create_and_fill_single(name, num * DIMS)
Definition at line 47 of file test_boris_particle_util.cpp.
Referenced by TEST().
#define create_and_fill_single (name, num)
Value:
create_single(name, num);\
  fill_single(name)
Definition at line 42 of file test_boris_particle_util.cpp.
Referenced by TEST().
#define create_cloud (name, num) create_single(name, num * DIMS)
Definition at line 45 of file test_boris_particle_util.cpp.
Referenced by TEST().
#define create_single (name, num) ParticleComponent<PRECISION> name(num)
Definition at line 40 of file test_boris_particle_util.cpp.
Referenced by TEST().
#define DIMS 3
Definition at line 15 of file test_boris_particle_util.cpp.
Referenced by TEST().
#define PRECISION double
Definition at line 16 of file test_boris_particle_util.cpp.
Referenced by TEST().
Function Documentation
void fill_single (ParticleComponent< PRECISION > & vec)
Definition at line 33 of file test_boris_particle_util.cpp.
References RandomGenerator::roll().
int main (int argc, char ** argv)
Definition at line 398 of file test_boris_particle_util.cpp.
TEST (OperatorTests , AddSingleOnSingle)
Definition at line 51 of file test_boris_particle_util.cpp.
References create_and_fill_single, create_single, and DIMS.
TEST (OperatorTests , AddCloudOnCloud)
Definition at line 63 of file test_boris_particle_util.cpp.
References create_and_fill_cloud, create_cloud, and DIMS.
TEST (OperatorTests , AddSingleOnCloud)
Definition at line 77 of file test_boris_particle_util.cpp.
References create_and_fill_cloud, create_and_fill_single, create_cloud, and DIMS.
TEST (OperatorTests , InplaceAddSingleOnSingle)
Definition at line 91 of file test_boris_particle_util.cpp.
References create_and_fill_single, create_single, and DIMS.
TEST (OperatorTests , InplaceAddCloudOnCloud)
Definition at line 103 of file test_boris_particle_util.cpp.
References create_and_fill_cloud, create_cloud, and DIMS.
TEST (OperatorTests , InplaceAddSingleOnCloud)
Definition at line 117 of file test_boris_particle_util.cpp.
References create_and_fill_cloud, create_and_fill_single, create_cloud, and DIMS.
TEST (OperatorTests , MinusSingleOnSingle)
Definition at line 131 of file test_boris_particle_util.cpp.
References create_and_fill_single, create_single, and DIMS.
TEST (OperatorTests , MinusCloudOnCloud)
Definition at line 143 of file test_boris_particle_util.cpp.
References create_and_fill_cloud, create_cloud, and DIMS.
TEST (OperatorTests , MinusSingleOnCloud)
Definition at line 157 of file test_boris_particle_util.cpp.
References create_and_fill_cloud, create_and_fill_single, create_cloud, and DIMS.
TEST (OperatorTests , InplaceMinusSingleOnSingle)
Definition at line 171 of file test_boris_particle_util.cpp.
References create_and_fill_single, create_single, and DIMS.
TEST (OperatorTests , InplaceMinusCloudOnCloud)
Definition at line 183 of file test_boris_particle_util.cpp.
References create_and_fill_cloud, create_cloud, and DIMS.
TEST (OperatorTests , InplaceMinusSingleOnCloud)
Definition at line 197 of file test_boris_particle_util.cpp.
References create_and_fill_cloud, create_and_fill_single, create_cloud, and DIMS.
TEST (OperatorTests , MulWithSingle)
Definition at line 211 of file test_boris_particle_util.cpp.
References create_and_fill_single, create_single, DIMS, and PRECISION.
TEST (OperatorTests , MulWithCloud)
Definition at line 225 of file test_boris_particle_util.cpp.
References create_and_fill_cloud, create_cloud, DIMS, and PRECISION.
TEST (OperatorTests , InplaceMulWithSingle)
Definition at line 241 of file test_boris_particle_util.cpp.
References create_and_fill_single, create_single, DIMS, and PRECISION.
TEST (OperatorTests , InplaceMulWithCloud)
Definition at line 253 of file test_boris_particle_util.cpp.
References create_and_fill_cloud, create_cloud, DIMS, and PRECISION.
TEST (OperatorTests , DivWithSingle)
Definition at line 267 of file test_boris_particle_util.cpp.
References create_and_fill_single, create_single, DIMS, and PRECISION.
TEST (OperatorTests , DivWithCloud)
Definition at line 279 of file test_boris_particle_util.cpp.
References create_and_fill_cloud, create_cloud, DIMS, and PRECISION.
TEST (OperatorTests , InplaceDivWithSingle)
Definition at line 293 of file test_boris_particle_util.cpp.
References create_and_fill_single, create_single, DIMS, and PRECISION.
TEST (OperatorTests , InplaceDivWithCloud)
Definition at line 305 of file test_boris_particle_util.cpp.
References create_and_fill_cloud, create_cloud, DIMS, and PRECISION.
TEST (OperatorTests , CrossProdSingleOnSingle)
Definition at line 319 of file test_boris_particle_util.cpp.
References create_and_fill_single, create_single, simple_physics_solver::internal::cross_prod(), and DIMS.
TEST (OperatorTests , CrossProdCloudOnCloud)
Definition at line 332 of file test_boris_particle_util.cpp.
References create_and_fill_cloud, create_cloud, simple_physics_solver::internal::cross_prod(), and DIMS.
TEST (OperatorTests , CrossProdSingleOnCloud)
Definition at line 346 of file test_boris_particle_util.cpp.
References create_and_fill_cloud, create_and_fill_single, create_cloud, simple_physics_solver::internal::cross_prod(), and DIMS.
TEST (UtilitiesTests , DistanceBetweenTwoParticles)
Definition at line 361 of file test_boris_particle_util.cpp.
References create_and_fill_single, DIMS, boris_analyse::distance(), pfasst::examples::boris::Particle< precision >::pos(), and PRECISION.
TEST (UtilitiesTests , DistanceOfCloudToReference)
Definition at line 378 of file test_boris_particle_util.cpp.
References create_and_fill_cloud, create_and_fill_single, DIMS, pfasst::examples::boris::distance_to_reference(), pfasst::examples::boris::Particle< precision >::pos(), and pfasst::examples::boris::ParticleCloud< precision >::positions().