PFASST++: pfasst::examples::boris::BorisSweeper< scalar, time > Class Template Reference
pfasst::examples::boris::BorisSweeper< scalar, time > Class Template Reference
Examples » Boris
#include <boris_sweeper.hpp>
Public Types
typedef ParticleCloud< scalar > encap_type
typedef ParticleCloudComponent< scalar > position_type
typedef ParticleCloudComponent< scalar > velocity_type
typedef ParticleCloudComponent< scalar > acceleration_type
Public Member Functions
BorisSweeper (shared_ptr< bindings::WrapperInterface< scalar, time >> &impl_solver, const string &data_file)
BorisSweeper (const BorisSweeper< scalar, time > &other)=delete
BorisSweeper (BorisSweeper< scalar, time > &&other)=delete
virtual ~BorisSweeper ()
virtual void set_state (shared_ptr< const encap_type > u0, size_t m)
virtual void set_start_state (shared_ptr< const encap_type > u0)
virtual shared_ptr< Encapsulation< time > > get_state (size_t m) const override
Retrieve solution values of current iteration at time node index m.
virtual shared_ptr< Encapsulation< time > > get_start_state () const
virtual shared_ptr< acceleration_type > get_tau_q_as_force (size_t m) const
virtual shared_ptr< acceleration_type > get_tau_qq_as_force (size_t m) const
virtual shared_ptr< Encapsulation< time > > get_saved_state (size_t m) const override
Retrieve solution values of previous iteration at time node index m.
virtual void set_initial_energy ()
virtual void exact (shared_ptr< Encapsulation< time >> q, time t)
virtual void exact (shared_ptr< encap_type > q, const time t)
virtual void exact (encap_type &q, const time t)
virtual void echo_error (const time t, bool predict=false)
virtual error_map< scalar > get_errors () const
virtual void setup (bool coarse=false) override
Setup (allocate etc) the sweeper.
virtual void integrate (time dt, vector< shared_ptr< Encapsulation< time >>> dst) const override
Integrates values of right hand side at all time nodes \(t \in [0,M-1] \) simultaneously.
virtual void integrate (time dt, vector< shared_ptr< acceleration_type >> dst_q, vector< shared_ptr< acceleration_type >> dst_qq) const
virtual void residual (time dt, vector< shared_ptr< Encapsulation< time >>> dst) const override
Compute residual at each SDC node (including FAS corrections).
virtual void advance () override
Advance from one time step to the next.
virtual void evaluate (size_t m)
virtual void predict (bool initial) override
Perform a predictor sweep.
virtual void sweep () override
Perform one SDC sweep/iteration.
virtual void save (bool initial_only=false) override
Save states (and/or function values) at all nodes.
virtual void spread () override
Initialize solution values at all time nodes with meaningful values.
virtual void post_sweep () override
Hook automatically run after each completed sweep.
virtual void post_predict () override
Hook automatically run after each completed predict.
virtual void post_step () override
Hook automatically run after each completed time step.
virtual void post (ICommunicator *comm, int tag) override
virtual void send (ICommunicator *comm, int tag, bool blocking) override
virtual void recv (ICommunicator *comm, int tag, bool blocking) override
virtual void broadcast (ICommunicator *comm) override
virtual void boris_solve (const time tm, const time t_next, const time ds, const size_t m, const velocity_type &c_k_term)
Public Member Functions inherited from pfasst::encap::EncapSweeper< time >
EncapSweeper ()
virtual shared_ptr< Encapsulation< time > > get_tau (size_t m) const
Retrieve FAS correction of current iteration at time node index m.
virtual void set_options () override
Set options from command line etc.
virtual void set_quadrature (shared_ptr< IQuadrature< time >> quadrature)
virtual shared_ptr< const IQuadrature< time > > get_quadrature () const
virtual const vector< time > get_nodes () const
virtual void set_factory (shared_ptr< EncapFactory< time >> factory)
virtual shared_ptr< EncapFactory< time > > get_factory () const
virtual shared_ptr< Encapsulation< time > > get_end_state ()
virtual void reevaluate (bool initial_only=false)
Re-evaluate function values.
void set_residual_tolerances (time abs_residual_tol, time rel_residual_tol, int order=0)
Set residual tolerances for convergence checking.
virtual bool converged () override
Return convergence status.
Public Member Functions inherited from pfasst::ISweeper< time >
ISweeper ()
virtual ~ISweeper ()
virtual void set_controller (Controller< time > *ctrl)
Set the sweepers controller.
virtual Controller< time > * get_controller ()
Accessor to the controller managing this sweeper.
Protected Member Functions
acceleration_type build_rhs (const size_t m, const bool previous=false) const
scalar compute_residual_max ()
void write_center_to_file (const size_t iter, const size_t sweep, const ParticleComponent< scalar > &center, const scalar energy, const scalar drift, const scalar residual)
void write_particle_cloud_to_file (const size_t iter, const size_t sweep, const shared_ptr< encap_type > &cloud, const scalar energy, const scalar drift, const scalar residual, const bool with_center=true)
void update_position (const size_t m, const time dt, const time ds)
void update_velocity (const size_t m, const time ds, const vector< time > &nodes)
Protected Attributes
vector< shared_ptr< encap_type > > particles
vector< shared_ptr< encap_type > > saved_particles
shared_ptr< encap_type > start_particles
shared_ptr< encap_type > end_particles
vector< shared_ptr< acceleration_type > > tau_q_corrections
vector< shared_ptr< acceleration_type > > tau_qq_corrections
vector< acceleration_type > forces
vector< acceleration_type > saved_forces
vector< acceleration_type > b_vecs
vector< acceleration_type > saved_b_vecs
scalar initial_energy
vector< scalar > energy_evals
size_t f_evals
bool coarse
vector< velocity_type > s_integrals
vector< position_type > ss_integrals
vector< time > delta_nodes
delta_nodes[m] = nodes[m] - nodes[m-1]
Matrix< time > s_mat
Matrix< time > ss_mat
Matrix< time > sx_mat
Matrix< time > st_mat
Matrix< time > q_mat
Matrix< time > qq_mat
Matrix< time > qx_mat
Matrix< time > qt_mat
ofstream data_stream
boost::format log_fmt
string DATA_STREAM_FORMAT_STR
boost::format data_stream_fmt
Protected Attributes inherited from pfasst::encap::EncapSweeper< time >
string FORMAT_STR
shared_ptr< IQuadrature< time > > quadrature
shared_ptr< EncapFactory< time > > factory
Encapsulation data structure factory.
shared_ptr< Encapsulation< time > > start_state
Separate start state, i.e. initial condition for the sweeper's current time step.
shared_ptr< Encapsulation< time > > end_state
Current solution at \(T_{end} \).
vector< shared_ptr< Encapsulation< time > > > residuals
Place for the residuals at the different time nodes.
vector< shared_ptr< Encapsulation< time > > > state
Solution values \(U \) at all time nodes of the current iteration.
vector< shared_ptr< Encapsulation< time > > > saved_state
Solution values \(U \) at all time nodes of the previous iteration.
vector< shared_ptr< Encapsulation< time > > > fas_corrections
FAS corrections \(\tau \) at all time nodes of the current iteration.
int residual_norm_order
time abs_residual_tol
Tolerance for absolute residual.
time rel_residual_tol
Tolerance for relative residual.
Protected Attributes inherited from pfasst::ISweeper< time >
Controller< time > * controller
Backreference to the controller managing the sweeper instance.
Private Attributes
shared_ptr< bindings::WrapperInterface< scalar, time > > impl_solver
error_map< scalar > errors
bool exact_updated
shared_ptr< encap_type > exact_cache
shared_ptr< LogIndent > log_indent
Detailed Description
template<typename scalar, typename time>
class pfasst::examples::boris::BorisSweeper< scalar, time >
Definition at line 123 of file boris_sweeper.hpp.
Member Typedef Documentation
template<typename scalar, typename time> typedef ParticleCloudComponent<scalar> pfasst::examples::boris::BorisSweeper< scalar, time >::acceleration_type
Definition at line 130 of file boris_sweeper.hpp.
template<typename scalar, typename time> typedef ParticleCloud<scalar> pfasst::examples::boris::BorisSweeper< scalar, time >::encap_type
Definition at line 127 of file boris_sweeper.hpp.
template<typename scalar, typename time> typedef ParticleCloudComponent<scalar> pfasst::examples::boris::BorisSweeper< scalar, time >::position_type
Definition at line 128 of file boris_sweeper.hpp.
template<typename scalar, typename time> typedef ParticleCloudComponent<scalar> pfasst::examples::boris::BorisSweeper< scalar, time >::velocity_type
Definition at line 129 of file boris_sweeper.hpp.
Constructor & Destructor Documentation
template<typename scalar, typename time> pfasst::examples::boris::BorisSweeper< scalar, time >::BorisSweeper (shared_ptr< bindings::WrapperInterface< scalar, time >> & impl_solver, const string & data_file)
Definition at line 237 of file boris_sweeper_impl.hpp.
References BCVLOG, pfasst::examples::boris::BorisSweeper< scalar, time >::data_stream, pfasst::examples::boris::BorisSweeper< scalar, time >::data_stream_fmt, and pfasst::examples::boris::BorisSweeper< scalar, time >::DATA_STREAM_FORMAT_STR.
template<typename scalar, typename time> pfasst::examples::boris::BorisSweeper< scalar, time >::BorisSweeper (const BorisSweeper< scalar, time > & other) delete
template<typename scalar, typename time> pfasst::examples::boris::BorisSweeper< scalar, time >::BorisSweeper (BorisSweeper< scalar, time > && other) delete
template<typename scalar , typename time > pfasst::examples::boris::BorisSweeper< scalar, time >::~BorisSweeper () virtual
Definition at line 257 of file boris_sweeper_impl.hpp.
Member Function Documentation
template<typename scalar , typename time > void pfasst::examples::boris::BorisSweeper< scalar, time >::advance () override virtual
Advance from one time step to the next.
Exceptions
NotImplementedYet This function is required by EncapSweeper
Reimplemented from pfasst::encap::EncapSweeper< time >.
Definition at line 615 of file boris_sweeper_impl.hpp.
References BCVLOG.
template<typename scalar , typename time> void pfasst::examples::boris::BorisSweeper< scalar, time >::boris_solve (const time tm, const time t_next, const time ds, const size_t m, const velocity_type & c_k_term) virtual
Definition at line 871 of file boris_sweeper_impl.hpp.
References BCVLOG, pfasst::examples::boris::cmp_wise_div(), pfasst::examples::boris::cross_prod(), pfasst::examples::boris::kronecker(), pfasst::examples::boris::norm_sq_npart(), and UNUSED.
template<typename scalar , typename time > void pfasst::examples::boris::BorisSweeper< scalar, time >::broadcast (ICommunicator * comm) override virtual
Reimplemented from pfasst::encap::EncapSweeper< time >.
Definition at line 862 of file boris_sweeper_impl.hpp.
References pfasst::ICommunicator::rank(), and pfasst::ICommunicator::size().
template<typename scalar , typename time > BorisSweeper< scalar, time >::acceleration_type pfasst::examples::boris::BorisSweeper< scalar, time >::build_rhs (const size_t m, const bool previous = false) const protected
Definition at line 103 of file boris_sweeper_impl.hpp.
References BCVLOG, and simple_physics_solver::internal::cross_prod().
template<typename scalar , typename time > scalar pfasst::examples::boris::BorisSweeper< scalar, time >::compute_residual_max () protected
Definition at line 123 of file boris_sweeper_impl.hpp.
References BCVLOG, and pfasst::examples::boris::max().
template<typename scalar , typename time> void pfasst::examples::boris::BorisSweeper< scalar, time >::echo_error (const time t, bool predict = false) virtual
Definition at line 393 of file boris_sweeper_impl.hpp.
References BCVLOG, pfasst::examples::boris::ErrorTuple< scalar >::e_drift, pfasst::examples::boris::ErrorTuple< scalar >::p_err, pfasst::examples::boris::ErrorTuple< scalar >::res, and pfasst::encap::solution.
template<typename scalar , typename time > void pfasst::examples::boris::BorisSweeper< scalar, time >::evaluate (size_t m) virtual
Definition at line 633 of file boris_sweeper_impl.hpp.
References BCVLOG, and plot::t.
template<typename scalar , typename time> void pfasst::examples::boris::BorisSweeper< scalar, time >::exact (shared_ptr< Encapsulation< time >> q, time t) virtual
Definition at line 323 of file boris_sweeper_impl.hpp.
template<typename scalar , typename time> void pfasst::examples::boris::BorisSweeper< scalar, time >::exact (shared_ptr< encap_type > q, const time t) virtual
Definition at line 331 of file boris_sweeper_impl.hpp.
template<typename scalar , typename time> void pfasst::examples::boris::BorisSweeper< scalar, time >::exact (encap_type & q, const time t) virtual
Definition at line 337 of file boris_sweeper_impl.hpp.
References BCVLOG, plot::dt, pfasst::examples::boris::ParticleCloud< precision >::positions(), plot::t, UNUSED, and pfasst::examples::boris::ParticleCloud< precision >::velocities().
template<typename scalar , typename time > error_map< scalar > pfasst::examples::boris::BorisSweeper< scalar, time >::get_errors () const virtual
Definition at line 428 of file boris_sweeper_impl.hpp.
template<typename scalar , typename time > shared_ptr< Encapsulation< time > > pfasst::examples::boris::BorisSweeper< scalar, time >::get_saved_state (size_t m) const override virtual
Retrieve solution values of previous iteration at time node index m.
Parameters
[in] m 0-based index of time node
Reimplemented from pfasst::encap::EncapSweeper< time >.
Definition at line 302 of file boris_sweeper_impl.hpp.
template<typename scalar , typename time > shared_ptr< Encapsulation< time > > pfasst::examples::boris::BorisSweeper< scalar, time >::get_start_state () const virtual
Reimplemented from pfasst::encap::EncapSweeper< time >.
Definition at line 282 of file boris_sweeper_impl.hpp.
template<typename scalar , typename time > shared_ptr< Encapsulation< time > > pfasst::examples::boris::BorisSweeper< scalar, time >::get_state (size_t m) const override virtual
Retrieve solution values of current iteration at time node index m.
Parameters
[in] m 0-based index of time node
Reimplemented from pfasst::encap::EncapSweeper< time >.
Definition at line 276 of file boris_sweeper_impl.hpp.
template<typename scalar , typename time > shared_ptr< typename BorisSweeper< scalar, time >::acceleration_type > pfasst::examples::boris::BorisSweeper< scalar, time >::get_tau_q_as_force (size_t m) const virtual
Definition at line 289 of file boris_sweeper_impl.hpp.
template<typename scalar , typename time > shared_ptr< typename BorisSweeper< scalar, time >::acceleration_type > pfasst::examples::boris::BorisSweeper< scalar, time >::get_tau_qq_as_force (size_t m) const virtual
Definition at line 296 of file boris_sweeper_impl.hpp.
template<typename scalar , typename time> void pfasst::examples::boris::BorisSweeper< scalar, time >::integrate (time dt, vector< shared_ptr< Encapsulation< time >>> dst) const override virtual
Integrates values of right hand side at all time nodes \(t \in [0,M-1] \) simultaneously.
Parameters
[in] dt width of the time interval to integrate
[in,out] dst integrated values
Exceptions
NotImplementedYet This function is required by EncapSweeper
Reimplemented from pfasst::encap::EncapSweeper< time >.
Definition at line 537 of file boris_sweeper_impl.hpp.
template<typename scalar , typename time> void pfasst::examples::boris::BorisSweeper< scalar, time >::integrate (time dt, vector< shared_ptr< acceleration_type >> dst_q, vector< shared_ptr< acceleration_type >> dst_qq) const virtual
Definition at line 543 of file boris_sweeper_impl.hpp.
References BCVLOG, plot::dt, and pfasst::examples::boris::zero().
template<typename scalar , typename time > void pfasst::examples::boris::BorisSweeper< scalar, time >::post (ICommunicator * comm, int tag) override virtual
Reimplemented from pfasst::encap::EncapSweeper< time >.
Definition at line 841 of file boris_sweeper_impl.hpp.
template<typename scalar , typename time > void pfasst::examples::boris::BorisSweeper< scalar, time >::post_predict () override virtual
Hook automatically run after each completed predict.
Reimplemented from pfasst::ISweeper< time >.
Definition at line 829 of file boris_sweeper_impl.hpp.
References plot::dt, and plot::t.
template<typename scalar , typename time > void pfasst::examples::boris::BorisSweeper< scalar, time >::post_step () override virtual
Hook automatically run after each completed time step.
Reimplemented from pfasst::ISweeper< time >.
Definition at line 837 of file boris_sweeper_impl.hpp.
template<typename scalar , typename time > void pfasst::examples::boris::BorisSweeper< scalar, time >::post_sweep () override virtual
Hook automatically run after each completed sweep.
Reimplemented from pfasst::ISweeper< time >.
Definition at line 821 of file boris_sweeper_impl.hpp.
References plot::dt, and plot::t.
template<typename scalar , typename time > void pfasst::examples::boris::BorisSweeper< scalar, time >::predict (bool initial) override virtual
Perform a predictor sweep.
Compute a provisional solution from the initial condition. This is typically very similar to a regular SDC sweep, except that integral terms based on previous iterations don't exist yet.
Parameters
[in] initial true if function values at the first node need to be computed. false if functions values at the first node already exist (usually this is the case when advancing from one time step to the next).
Implements pfasst::ISweeper< time >.
Definition at line 662 of file boris_sweeper_impl.hpp.
References BCVLOG.
template<typename scalar , typename time > void pfasst::examples::boris::BorisSweeper< scalar, time >::recv (ICommunicator * comm, int tag, bool blocking) override virtual
Reimplemented from pfasst::encap::EncapSweeper< time >.
Definition at line 853 of file boris_sweeper_impl.hpp.
template<typename scalar , typename time> void pfasst::examples::boris::BorisSweeper< scalar, time >::residual (time dt, vector< shared_ptr< Encapsulation< time >>> dst) const override virtual
Compute residual at each SDC node (including FAS corrections).
Parameters
[in] dt width of the time interval to compute the residual for
[in,out] dst place to store the residuals at time nodes
Exceptions
NotImplementedYet This function is required by EncapSweeper for residual computation
Reimplemented from pfasst::encap::EncapSweeper< time >.
Definition at line 572 of file boris_sweeper_impl.hpp.
References BCVLOG, and pfasst::examples::boris::zero().
template<typename scalar , typename time > void pfasst::examples::boris::BorisSweeper< scalar, time >::save (bool initial_only = false) override virtual
Save states (and/or function values) at all nodes.
Reimplemented from pfasst::encap::EncapSweeper< time >.
Definition at line 787 of file boris_sweeper_impl.hpp.
References BCVLOG.
template<typename scalar , typename time > void pfasst::examples::boris::BorisSweeper< scalar, time >::send (ICommunicator * comm, int tag, bool blocking) override virtual
Reimplemented from pfasst::encap::EncapSweeper< time >.
Definition at line 847 of file boris_sweeper_impl.hpp.
template<typename scalar , typename time > void pfasst::examples::boris::BorisSweeper< scalar, time >::set_initial_energy () virtual
Definition at line 308 of file boris_sweeper_impl.hpp.
References BCVLOG.
template<typename scalar , typename time > void pfasst::examples::boris::BorisSweeper< scalar, time >::set_start_state (shared_ptr< const encap_type > u0) virtual
Definition at line 270 of file boris_sweeper_impl.hpp.
template<typename scalar , typename time > void pfasst::examples::boris::BorisSweeper< scalar, time >::set_state (shared_ptr< const encap_type > u0, size_t m) virtual
Definition at line 264 of file boris_sweeper_impl.hpp.
template<typename scalar , typename time > void pfasst::examples::boris::BorisSweeper< scalar, time >::setup (bool coarse = false) override virtual
Setup (allocate etc) the sweeper.
Reimplemented from pfasst::encap::EncapSweeper< time >.
Definition at line 434 of file boris_sweeper_impl.hpp.
References BCVLOG, pfasst::encap::EncapSweeper< time >::setup(), pfasst::encap::solution, and UNUSED.
template<typename scalar , typename time > void pfasst::examples::boris::BorisSweeper< scalar, time >::spread () override virtual
Initialize solution values at all time nodes with meaningful values.
This implementation simply copies the initial value (see EncapSweeper::get_start_state()) to all time nodes.
Reimplemented from pfasst::encap::EncapSweeper< time >.
Definition at line 813 of file boris_sweeper_impl.hpp.
template<typename scalar , typename time > void pfasst::examples::boris::BorisSweeper< scalar, time >::sweep () override virtual
Perform one SDC sweep/iteration.
Compute a correction and update solution values. Note that this function can assume that valid function values exist from a previous pfasst::ISweeper::sweep() or pfasst::ISweeper::predict().
Implements pfasst::ISweeper< time >.
Definition at line 682 of file boris_sweeper_impl.hpp.
References BCVLOG, plot::dt, plot::t, and pfasst::examples::boris::zero().
template<typename scalar , typename time> void pfasst::examples::boris::BorisSweeper< scalar, time >::update_position (const size_t m, const time dt, const time ds) protected
Definition at line 180 of file boris_sweeper_impl.hpp.
References BCVLOG.
template<typename scalar , typename time> void pfasst::examples::boris::BorisSweeper< scalar, time >::update_velocity (const size_t m, const time ds, const vector< time > & nodes) protected
Definition at line 207 of file boris_sweeper_impl.hpp.
References BCVLOG, and pfasst::examples::boris::zero().
template<typename scalar, typename time > void pfasst::examples::boris::BorisSweeper< scalar, time >::write_center_to_file (const size_t iter, const size_t sweep, const ParticleComponent< scalar > & center, const scalar energy, const scalar drift, const scalar residual) protected
Definition at line 143 of file boris_sweeper_impl.hpp.
References BCVLOG.
template<typename scalar, typename time > void pfasst::examples::boris::BorisSweeper< scalar, time >::write_particle_cloud_to_file (const size_t iter, const size_t sweep, const shared_ptr< encap_type > & cloud, const scalar energy, const scalar drift, const scalar residual, const bool with_center = true) protected
Definition at line 157 of file boris_sweeper_impl.hpp.
References BCVLOG.
Member Data Documentation
template<typename scalar, typename time> vector<acceleration_type> pfasst::examples::boris::BorisSweeper< scalar, time >::b_vecs protected
Definition at line 149 of file boris_sweeper.hpp.
template<typename scalar, typename time> bool pfasst::examples::boris::BorisSweeper< scalar, time >::coarse protected
Definition at line 156 of file boris_sweeper.hpp.
template<typename scalar, typename time> ofstream pfasst::examples::boris::BorisSweeper< scalar, time >::data_stream protected
Definition at line 173 of file boris_sweeper.hpp.
Referenced by pfasst::examples::boris::BorisSweeper< scalar, time >::BorisSweeper().
template<typename scalar, typename time> boost::format pfasst::examples::boris::BorisSweeper< scalar, time >::data_stream_fmt protected
Definition at line 177 of file boris_sweeper.hpp.
Referenced by pfasst::examples::boris::BorisSweeper< scalar, time >::BorisSweeper().
template<typename scalar, typename time> string pfasst::examples::boris::BorisSweeper< scalar, time >::DATA_STREAM_FORMAT_STR protected
Definition at line 176 of file boris_sweeper.hpp.
Referenced by pfasst::examples::boris::BorisSweeper< scalar, time >::BorisSweeper().
template<typename scalar, typename time> vector<time> pfasst::examples::boris::BorisSweeper< scalar, time >::delta_nodes protected
delta_nodes[m] = nodes[m] - nodes[m-1]
Definition at line 162 of file boris_sweeper.hpp.
template<typename scalar, typename time> shared_ptr<encap_type> pfasst::examples::boris::BorisSweeper< scalar, time >::end_particles protected
Definition at line 143 of file boris_sweeper.hpp.
template<typename scalar, typename time> vector<scalar> pfasst::examples::boris::BorisSweeper< scalar, time >::energy_evals protected
Definition at line 153 of file boris_sweeper.hpp.
template<typename scalar, typename time> error_map<scalar> pfasst::examples::boris::BorisSweeper< scalar, time >::errors private
Definition at line 134 of file boris_sweeper.hpp.
template<typename scalar, typename time> shared_ptr<encap_type> pfasst::examples::boris::BorisSweeper< scalar, time >::exact_cache private
Definition at line 136 of file boris_sweeper.hpp.
template<typename scalar, typename time> bool pfasst::examples::boris::BorisSweeper< scalar, time >::exact_updated private
Definition at line 135 of file boris_sweeper.hpp.
template<typename scalar, typename time> size_t pfasst::examples::boris::BorisSweeper< scalar, time >::f_evals protected
Definition at line 154 of file boris_sweeper.hpp.
template<typename scalar, typename time> vector<acceleration_type> pfasst::examples::boris::BorisSweeper< scalar, time >::forces protected
Definition at line 147 of file boris_sweeper.hpp.
template<typename scalar, typename time> shared_ptr<bindings::WrapperInterface<scalar, time> > pfasst::examples::boris::BorisSweeper< scalar, time >::impl_solver private
Definition at line 133 of file boris_sweeper.hpp.
template<typename scalar, typename time> scalar pfasst::examples::boris::BorisSweeper< scalar, time >::initial_energy protected
Definition at line 152 of file boris_sweeper.hpp.
template<typename scalar, typename time> boost::format pfasst::examples::boris::BorisSweeper< scalar, time >::log_fmt protected
Definition at line 175 of file boris_sweeper.hpp.
template<typename scalar, typename time> shared_ptr<LogIndent> pfasst::examples::boris::BorisSweeper< scalar, time >::log_indent private
Definition at line 137 of file boris_sweeper.hpp.
template<typename scalar, typename time> vector<shared_ptr<encap_type> > pfasst::examples::boris::BorisSweeper< scalar, time >::particles protected
Definition at line 140 of file boris_sweeper.hpp.
template<typename scalar, typename time> Matrix<time> pfasst::examples::boris::BorisSweeper< scalar, time >::q_mat protected
Definition at line 168 of file boris_sweeper.hpp.
template<typename scalar, typename time> Matrix<time> pfasst::examples::boris::BorisSweeper< scalar, time >::qq_mat protected
Definition at line 169 of file boris_sweeper.hpp.
template<typename scalar, typename time> Matrix<time> pfasst::examples::boris::BorisSweeper< scalar, time >::qt_mat protected
Definition at line 171 of file boris_sweeper.hpp.
template<typename scalar, typename time> Matrix<time> pfasst::examples::boris::BorisSweeper< scalar, time >::qx_mat protected
Definition at line 170 of file boris_sweeper.hpp.
template<typename scalar, typename time> vector<velocity_type> pfasst::examples::boris::BorisSweeper< scalar, time >::s_integrals protected
Definition at line 158 of file boris_sweeper.hpp.
template<typename scalar, typename time> Matrix<time> pfasst::examples::boris::BorisSweeper< scalar, time >::s_mat protected
Definition at line 164 of file boris_sweeper.hpp.
template<typename scalar, typename time> vector<acceleration_type> pfasst::examples::boris::BorisSweeper< scalar, time >::saved_b_vecs protected
Definition at line 150 of file boris_sweeper.hpp.
template<typename scalar, typename time> vector<acceleration_type> pfasst::examples::boris::BorisSweeper< scalar, time >::saved_forces protected
Definition at line 148 of file boris_sweeper.hpp.
template<typename scalar, typename time> vector<shared_ptr<encap_type> > pfasst::examples::boris::BorisSweeper< scalar, time >::saved_particles protected
Definition at line 141 of file boris_sweeper.hpp.
template<typename scalar, typename time> vector<position_type> pfasst::examples::boris::BorisSweeper< scalar, time >::ss_integrals protected
Definition at line 159 of file boris_sweeper.hpp.
template<typename scalar, typename time> Matrix<time> pfasst::examples::boris::BorisSweeper< scalar, time >::ss_mat protected
Definition at line 165 of file boris_sweeper.hpp.
template<typename scalar, typename time> Matrix<time> pfasst::examples::boris::BorisSweeper< scalar, time >::st_mat protected
Definition at line 167 of file boris_sweeper.hpp.
template<typename scalar, typename time> shared_ptr<encap_type> pfasst::examples::boris::BorisSweeper< scalar, time >::start_particles protected
Definition at line 142 of file boris_sweeper.hpp.
template<typename scalar, typename time> Matrix<time> pfasst::examples::boris::BorisSweeper< scalar, time >::sx_mat protected
Definition at line 166 of file boris_sweeper.hpp.
template<typename scalar, typename time> vector<shared_ptr<acceleration_type> > pfasst::examples::boris::BorisSweeper< scalar, time >::tau_q_corrections protected
Definition at line 145 of file boris_sweeper.hpp.
template<typename scalar, typename time> vector<shared_ptr<acceleration_type> > pfasst::examples::boris::BorisSweeper< scalar, time >::tau_qq_corrections protected
Definition at line 146 of file boris_sweeper.hpp.
The documentation for this class was generated from the following files:
examples/boris/boris_sweeper.hpp
examples/boris/boris_sweeper_impl.hpp