PFASST++: boris_analyse Namespace Reference
boris_analyse Namespace Reference
Classes
class BorisData
Functions
def distance (a, b)
def get_meetup_after
def plot_trajectories
def plot_analytics
def plot_particle_meetup
Variables
list colors = ['b', 'r', 'y', 'c', 'm']
Function Documentation
def boris_analyse.distance (a, b)
Definition at line 11 of file boris_analyse.py.
Referenced by boris_analyse.BorisData._read_data(), and TEST().
def boris_analyse.get_meetup_after (data, after = 0)
Definition at line 178 of file boris_analyse.py.
def boris_analyse.plot_analytics (data, start = 0, until = None, wo_drift = False)
Definition at line 207 of file boris_analyse.py.
Referenced by plot_particle_meetup().
def boris_analyse.plot_particle_meetup (data, step, width = 10)
Definition at line 260 of file boris_analyse.py.
References plot_analytics().
def boris_analyse.plot_trajectories (data, until = None)
Definition at line 183 of file boris_analyse.py.
Variable Documentation
list boris_analyse.colors = ['b', 'r', 'y', 'c', 'm']
Definition at line 8 of file boris_analyse.py.