PFASST++: pfasst::MLSDC< time > Class Template Reference
pfasst::MLSDC< time > Class Template Reference
Controllers
Multilevel SDC controller.
#include <mlsdc.hpp>
Public Member Functions
virtual void setup () override
Basic setup routine for this controller.
virtual void set_nsweeps (vector< size_t > nsweeps)
Set desired number of sweeps for each level independently.
virtual void run ()
Solve ODE using MLSDC.
Public Member Functions inherited from pfasst::Controller< time >
Controller ()
virtual ~Controller ()
virtual void set_options (bool all_sweepers=true)
Set options from command line etc.
virtual void set_duration (time t0, time tend, time dt, size_t niters)
Set basic time scope of the Controller.
virtual void add_level (shared_ptr< ISweeper< time >> sweeper, shared_ptr< ITransfer< time >> transfer=shared_ptr< ITransfer< time >>(nullptr), bool coarse=true)
Adding a level to the controller.
virtual size_t nlevels ()
Total number of levels controlled by this Controller.
template<typename R = ISweeper<time>>
shared_ptr< R > get_level (size_t level)
Get sweeper for level with index level.
template<typename R = ISweeper<time>>
shared_ptr< R > get_finest ()
Get coarsest level.
template<typename R = ISweeper<time>>
shared_ptr< R > get_coarsest ()
Get coarsest level.
template<typename R = ITransfer<time>>
shared_ptr< R > get_transfer (size_t level)
Retreive transfer operator for level level.
virtual size_t get_step ()
Get current time step index.
virtual void set_step (size_t n)
Set current time step index.
virtual time get_step_size ()
Get width of current time step.
time get_dt ()
Get width of current time step (alias for get_step_size).
virtual time get_time ()
Get start time point of current time step.
time get_t ()
Get start time point of current time step (alias for get_time).
virtual void advance_time (size_t nsteps=1)
Advance to a following time step.
virtual time get_end_time ()
Get end time point of last time step.
virtual size_t get_iteration ()
Get current iteration index of current time step.
virtual void set_iteration (size_t iter)
Set current iteration of current time step.
virtual void advance_iteration ()
Advance to the next iteration.
virtual size_t get_max_iterations ()
Get maximum number of allowed iterations per time step.
virtual LevelIter finest ()
Convenience accessor to the finest level.
virtual LevelIter coarsest ()
Convenience accessor to the coarsest level.
Protected Types
typedef pfasst::Controller< time >::LevelIter LevelIter
Protected Member Functions
void perform_sweeps (size_t level)
Perform pre-configured number of sweeps on level level.
Protected Attributes
vector< size_t > nsweeps
How many sweeps should be done on the different levels.
bool predict
Whether to use a predict sweep.
bool initial
Whether we're sweeping from a new initial condition.
bool converged
Whether we've converged.
Protected Attributes inherited from pfasst::Controller< time >
deque< shared_ptr< ISweeper< time > > > levels
Ordered list of all levels.
deque< shared_ptr< ITransfer< time > > > transfer
Ordered list of transfer operators for levels.
size_t step
Current time step index.
size_t iteration
Current iteration index on current time step.
size_t max_iterations
Maximum iterations per time step.
time t
\(t_0 \) of current time step.
time dt
Width of current time step (\(\Delta t \)).
time tend
\(T_{end} \) of last time step.
Private Member Functions
LevelIter cycle_down (LevelIter level_iter)
Sweep on current (fine), restrict to coarse.
LevelIter cycle_up (LevelIter level_iter)
Interpolate coarse correction to fine, sweep on current (fine).
LevelIter cycle_bottom (LevelIter level_iter)
Sweep on the current (coarsest) level.
LevelIter cycle_v (LevelIter level_iter)
Perform an MLSDC V-cycle.
Detailed Description
template<typename time = pfasst::time_precision>
class pfasst::MLSDC< time >
Multilevel SDC controller.
Template Parameters
time time precision
Definition at line 24 of file mlsdc.hpp.
Member Typedef Documentation
template<typename time = pfasst::time_precision> typedef pfasst::Controller<time>::LevelIter pfasst::MLSDC< time >::LevelIter protected
Definition at line 30 of file mlsdc.hpp.
Member Function Documentation
template<typename time = pfasst::time_precision> MLSDC< time >::LevelIter pfasst::MLSDC< time >::cycle_bottom (LevelIter level_iter) private
Sweep on the current (coarsest) level.
Parameters
[in] level_iter level iterator pointing to the coarsest level
Returns
level iterator pointing to the next finer level
Precondition
It is assumed that level_iter currently points to the coarsest level.
Definition at line 145 of file mlsdc_impl.hpp.
References pfasst::Controller< time >::LevelIter::level.
template<typename time = pfasst::time_precision> MLSDC< time >::LevelIter pfasst::MLSDC< time >::cycle_down (LevelIter level_iter) private
Sweep on current (fine), restrict to coarse.
First, MLSDC::perform_sweeps() with current level is called followed by a check on convergence via ISweeper::converged() on the same level.
Parameters
[in] level_iter level iterator pointing to the finer level
Returns
level iterator to current level if it has converged after the sweep; otherwise a level iterator to the next coarser level
If it has not converged the transfer operator of the current level is used to restrict from current to coarse via ITransfer::restrict() (under consideration of MLSDC::initial). The FAS correction is computed via the same transfer operators ITransfer::fas() method.
A call to ISweeper::save() finalizes the restriction on the coarser level.
Definition at line 99 of file mlsdc_impl.hpp.
References pfasst::Controller< time >::LevelIter::coarse(), pfasst::Controller< time >::LevelIter::current(), pfasst::Controller< time >::LevelIter::level, ML_CVLOG, and pfasst::Controller< time >::LevelIter::transfer().
template<typename time = pfasst::time_precision> MLSDC< time >::LevelIter pfasst::MLSDC< time >::cycle_up (LevelIter level_iter) private
Interpolate coarse correction to fine, sweep on current (fine).
First the transfer operator of the current level is used (via ITransfer::interpolate()) to interpolate from the coarser level to the current (finer) level.
Parameters
[in] level_iter level iterator pointing to the finer level
Returns
level iterator pointing to the coarser level
Note
If the fine level corresponds to the finest MLSDC level, we don't perform a sweep. In this case the only operation that is performed here is interpolation.
Definition at line 128 of file mlsdc_impl.hpp.
References pfasst::Controller< time >::LevelIter::coarse(), pfasst::Controller< time >::LevelIter::current(), pfasst::Controller< time >::LevelIter::level, ML_CVLOG, and pfasst::Controller< time >::LevelIter::transfer().
template<typename time = pfasst::time_precision> MLSDC< time >::LevelIter pfasst::MLSDC< time >::cycle_v (LevelIter level_iter) private
Perform an MLSDC V-cycle.
Parameters
[in] level_iter level iterator pointing to a fine level
Returns
level iterator pointing to either the coarsest level if level_iter is the coarsest level or the same level as level_iter if a sweep on that level results in convergence or all sweeps on all coarser levels did not let to convergence
Note
This method is recursive with two exit points. The two exit points:
if level_iter points to the coarsest level
if MLSDC::cycle_down() results in a converged state
Definition at line 158 of file mlsdc_impl.hpp.
References pfasst::Controller< time >::LevelIter::level.
template<typename time > void pfasst::MLSDC< time >::perform_sweeps (size_t level) protected
Perform pre-configured number of sweeps on level level.
One sweep is either a call to ISweeper::predict() if MLSDC::predict is true followed by triggering the ISweeper::post_predict() hook.
Parameters
[in] level level index to perform pre-configured number of sweeps
See also
set_nsweeps() for pre-configuring number of sweeps
In case MLSDC::predict is false, ISweeper::sweep() and subsequent ISweeper::post_sweep() are called.
Note
There is no check on convergence here.
Definition at line 20 of file mlsdc_impl.hpp.
References ML_CVLOG.
template<typename time > void pfasst::MLSDC< time >::run () virtual
Solve ODE using MLSDC.
Precondition
It is assumed that the user has set initial conditions on the finest level.
Reimplemented in pfasst::PFASST< time >.
Definition at line 62 of file mlsdc_impl.hpp.
Referenced by pfasst::PFASST< time >::run(), pfasst::examples::boris::run_boris_sdc(), and pfasst::examples::advection_diffusion::run_serial_mlsdc().
template<typename time > void pfasst::MLSDC< time >::set_nsweeps (vector< size_t > nsweeps) virtual
Set desired number of sweeps for each level independently.
Parameters
[in] nsweeps vector with number of sweeps for each level.
Note
The same level indicing as with Controller::levels applies.
Definition at line 56 of file mlsdc_impl.hpp.
Referenced by pfasst::examples::advection_diffusion::run_mpi_pfasst().
template<typename time > void pfasst::MLSDC< time >::setup () override virtual
Basic setup routine for this controller.
Precondition
It is expected (i.e. the user has to make that sure) that all levels and transfer operators have been instantiated and added to this controller before calling Controller::setup().
Note
To overwrite the default behaviour of a single sweep per level, the user must call MLSDC::set_nsweeps() after MLSDC::setup().
Reimplemented from pfasst::Controller< time >.
Definition at line 45 of file mlsdc_impl.hpp.
Referenced by pfasst::examples::boris::run_boris_pfasst(), pfasst::examples::boris::run_boris_sdc(), pfasst::examples::advection_diffusion::run_mpi_pfasst(), and pfasst::examples::advection_diffusion::run_serial_mlsdc().
Member Data Documentation
template<typename time = pfasst::time_precision> bool pfasst::MLSDC< time >::converged protected
Whether we've converged.
Definition at line 34 of file mlsdc.hpp.
template<typename time = pfasst::time_precision> bool pfasst::MLSDC< time >::initial protected
Whether we're sweeping from a new initial condition.
Definition at line 33 of file mlsdc.hpp.
template<typename time = pfasst::time_precision> vector<size_t> pfasst::MLSDC< time >::nsweeps protected
How many sweeps should be done on the different levels.
Definition at line 28 of file mlsdc.hpp.
template<typename time = pfasst::time_precision> bool pfasst::MLSDC< time >::predict protected
Whether to use a predict sweep.
Definition at line 32 of file mlsdc.hpp.
The documentation for this class was generated from the following files:
include/pfasst/controller/mlsdc.hpp
src/pfasst/controller/mlsdc_impl.hpp