
PFASST := $(abspath ../../..)

TESTS    := test_advection_diffusion
MPITESTS := test_mpi_advection_diffusion
TESTLIBS := -lfftw3

include $(PFASST)/tests/Makefile.tests
include $(PFASST)/tools/make/Makefile.inc
