PFASST++: pfasst Namespace Reference
pfasst Namespace Reference
Namespaces
config
encap
Encapsulations (short encaps) are the central data type for all PFASST++ algorithms.
examples
log
Logging facilities for PFASST++.
mpi
quadrature
Functionality related to computing quadrature nodes and weights.
Classes
class Controller
Base SDC/MLSDC/PFASST controller.
class ICommunicator
Abstract interface for communicators.
class IStatus
Abstract interface for the current status of the algorithm.
class ISweeper
Abstract SDC sweeper.
class ITransfer
Abstract time/space transfer (restrict/interpolate) class.
class MLSDC
Multilevel SDC controller.
class NotImplementedYet
Not implemented yet exception.
class PFASST
Implementation of the PFASST algorithm as described in [1] .
class SDC
Vanilla SDC controller.
class ValueError
Value exception.
Typedefs
using time_precision = double
Functions
static void init (int argc, char **argv, std::function< void()> opts=nullptr, std::function< void()> logs=nullptr)
Variables
static constexpr const char * VERSION = "v0.5.0-rc1-48-g4da93b0-dirty"
PFASST++ version: closest release tag and a brief git hash.
Typedef Documentation
using pfasst::time_precision = typedef double
Definition at line 18 of file interfaces.hpp.
Function Documentation
static void pfasst::init (int argc, char ** argv, std::function< void()> opts = nullptr, std::function< void()> logs = nullptr) inline static
Definition at line 13 of file pfasst.hpp.
References pfasst::config::read_commandline(), and pfasst::log::start_log().
Referenced by main().