PFASST++: ConvergenceTest Class Reference
ConvergenceTest Class Reference
Public Member Functions
virtual void SetUp ()
virtual void SetUp ()
virtual void SetUp ()
Protected Attributes
size_t nnodes
size_t niters
size_t nlevs = 3
vector< size_t > nsteps
vector< double > err
vector< double > convrate
pfasst::quadrature::QuadratureType nodetype
double end_time
complex< double > lambda
Detailed Description
Definition at line 21 of file test_advection_diffusion_conv.cpp.
Member Function Documentation
virtual void ConvergenceTest::SetUp () inline virtual
Definition at line 33 of file test_mpi_advection_diffusion_conv.cpp.
References pfasst::quadrature::ClenshawCurtis, plot::dt, pfasst::quadrature::GaussLegendre, pfasst::quadrature::GaussLobatto, pfasst::examples::advection_diffusion::run_mpi_pfasst(), and pfasst::quadrature::Uniform.
virtual void ConvergenceTest::SetUp () inline virtual
Definition at line 34 of file test_advection_diffusion_conv.cpp.
References pfasst::quadrature::ClenshawCurtis, plot::dt, pfasst::quadrature::GaussLegendre, pfasst::quadrature::GaussLobatto, pfasst::examples::advection_diffusion::run_serial_mlsdc(), and pfasst::quadrature::Uniform.
virtual void ConvergenceTest::SetUp () inline virtual
Definition at line 35 of file test_scalar_conv.cpp.
References pfasst::quadrature::ClenshawCurtis, plot::dt, pfasst::quadrature::GaussLegendre, pfasst::quadrature::GaussLobatto, pfasst::quadrature::GaussRadau, pfasst::examples::scalar::run_scalar_sdc(), and pfasst::quadrature::Uniform.
Member Data Documentation
vector< double > ConvergenceTest::convrate protected
Definition at line 30 of file test_advection_diffusion_conv.cpp.
double ConvergenceTest::end_time protected
Definition at line 27 of file test_scalar_conv.cpp.
vector< double > ConvergenceTest::err protected
Definition at line 29 of file test_advection_diffusion_conv.cpp.
complex<double> ConvergenceTest::lambda protected
Definition at line 31 of file test_scalar_conv.cpp.
size_t ConvergenceTest::niters protected
Definition at line 26 of file test_advection_diffusion_conv.cpp.
size_t ConvergenceTest::nlevs = 3 protected
Definition at line 27 of file test_advection_diffusion_conv.cpp.
size_t ConvergenceTest::nnodes protected
Definition at line 25 of file test_advection_diffusion_conv.cpp.
pfasst::quadrature::QuadratureType ConvergenceTest::nodetype protected
Definition at line 31 of file test_advection_diffusion_conv.cpp.
vector< size_t > ConvergenceTest::nsteps protected
Definition at line 28 of file test_advection_diffusion_conv.cpp.
Referenced by boris_analyse.BorisData::_read_data().
The documentation for this class was generated from the following files:
tests/examples/advection_diffusion/test_advection_diffusion_conv.cpp
tests/examples/advection_diffusion/test_mpi_advection_diffusion_conv.cpp
tests/examples/scalar/test_scalar_conv.cpp