PFASST++: simple_physics_solver::internal Namespace Reference
simple_physics_solver::internal Namespace Reference
Examples » Boris » Bindings » External Solver
Functions
void cross_prod (const double first[DIM], const double second[DIM], double cross_prod[DIM])
double scalar_prod (const double first[DIM], const double second[DIM])
void scale_mat_mul_vec (const double mat[DIM][DIM], const double vec[DIM], const double factor, double prod[DIM])
void print_vec (const double vec[DIM])
Function Documentation
void simple_physics_solver::internal::cross_prod (const double first[DIM], const double second[DIM], double cross_prod[DIM]) inline
Definition at line 228 of file simple_physics_solver.cpp.
Referenced by pfasst::examples::boris::BorisSweeper< scalar, time >::build_rhs(), and TEST().
void simple_physics_solver::internal::print_vec (const double vec[DIM]) inline
Definition at line 255 of file simple_physics_solver.cpp.
References DIM.
double simple_physics_solver::internal::scalar_prod (const double first[DIM], const double second[DIM]) inline
Definition at line 235 of file simple_physics_solver.cpp.
References DIM.
Referenced by simple_physics_solver::compute_energy().
void simple_physics_solver::internal::scale_mat_mul_vec (const double mat[DIM][DIM], const double vec[DIM], const double factor, double prod[DIM]) inline
Definition at line 244 of file simple_physics_solver.cpp.
References DIM.
Referenced by simple_physics_solver::compute_energy(), simple_physics_solver::evaluate_b_field(), and simple_physics_solver::evaluate_external_e_field().