PFASST++: pfasst::quadrature::GaussLegendre< precision > Class Template Reference
pfasst::quadrature::GaussLegendre< precision > Class Template Reference
Quadrature handler for Gauss-Legendre quadrature.
#include <gauss_legendre.hpp>
Public Member Functions
GaussLegendre (const size_t num_nodes)
GaussLegendre ()=default
virtual ~GaussLegendre ()=default
virtual bool left_is_node () const override
virtual bool right_is_node () const override
Public Member Functions inherited from pfasst::quadrature::IQuadrature< precision >
precision expected_error () const
Compute a rough estimate of the numerical error...
IQuadrature (const size_t num_nodes)
IQuadrature ()
virtual ~IQuadrature ()=default
virtual const Matrix< precision > & get_q_mat () const
virtual const Matrix< precision > & get_s_mat () const
virtual const Matrix< precision > & get_b_mat () const
virtual const vector< precision > & get_q_vec () const
virtual const vector< precision > & get_nodes () const
virtual size_t get_num_nodes () const
Protected Member Functions
virtual void compute_nodes () override
Protected Member Functions inherited from pfasst::quadrature::IQuadrature< precision >
virtual void compute_weights ()
Static Protected Attributes
static const bool LEFT_IS_NODE = false
static const bool RIGHT_IS_NODE = false
Static Protected Attributes inherited from pfasst::quadrature::IQuadrature< precision >
static const bool LEFT_IS_NODE = false
static const bool RIGHT_IS_NODE = false
Additional Inherited Members
Protected Attributes inherited from pfasst::quadrature::IQuadrature< precision >
size_t num_nodes
Matrix< precision > q_mat
Matrix< precision > s_mat
vector< precision > q_vec
Matrix< precision > b_mat
vector< precision > nodes
Detailed Description
template<typename precision = pfasst::time_precision>
class pfasst::quadrature::GaussLegendre< precision >
Quadrature handler for Gauss-Legendre quadrature.
Template Parameters
scalar precision of quadrature (i.e. double)
Since
v0.3.0
Definition at line 23 of file gauss_legendre.hpp.
Constructor & Destructor Documentation
template<typename precision > pfasst::quadrature::GaussLegendre< precision >::GaussLegendre (const size_t num_nodes) explicit
Definition at line 14 of file gauss_legendre_impl.hpp.
References pfasst::quadrature::GaussLegendre< precision >::compute_nodes(), and pfasst::quadrature::IQuadrature< precision >::compute_weights().
template<typename precision = pfasst::time_precision> pfasst::quadrature::GaussLegendre< precision >::GaussLegendre () default
template<typename precision = pfasst::time_precision> virtual pfasst::quadrature::GaussLegendre< precision >::~GaussLegendre () virtual default
Member Function Documentation
template<typename precision > void pfasst::quadrature::GaussLegendre< precision >::compute_nodes () override protected virtual
Exceptions
pfasst::NotImplementedYet if not overwritten by implementation; required for quadrature of any kind
Reimplemented from pfasst::quadrature::IQuadrature< precision >.
Definition at line 34 of file gauss_legendre_impl.hpp.
References pfasst::quadrature::Polynomial< CoeffT >::legendre().
Referenced by pfasst::quadrature::GaussLegendre< precision >::GaussLegendre().
template<typename precision > bool pfasst::quadrature::GaussLegendre< precision >::left_is_node () const override virtual
Exceptions
pfasst::NotImplementedYet if not overwritten by implementation; required for quadrature of any kind
Reimplemented from pfasst::quadrature::IQuadrature< precision >.
Definition at line 22 of file gauss_legendre_impl.hpp.
template<typename precision > bool pfasst::quadrature::GaussLegendre< precision >::right_is_node () const override virtual
Exceptions
pfasst::NotImplementedYet if not overwritten by implementation; required for quadrature of any kind
Reimplemented from pfasst::quadrature::IQuadrature< precision >.
Definition at line 28 of file gauss_legendre_impl.hpp.
Member Data Documentation
template<typename precision = pfasst::time_precision> const bool pfasst::quadrature::GaussLegendre< precision >::LEFT_IS_NODE = false static protected
Definition at line 28 of file gauss_legendre.hpp.
template<typename precision = pfasst::time_precision> const bool pfasst::quadrature::GaussLegendre< precision >::RIGHT_IS_NODE = false static protected
Definition at line 29 of file gauss_legendre.hpp.
The documentation for this class was generated from the following files:
include/pfasst/quadrature/gauss_legendre.hpp
src/pfasst/quadrature/gauss_legendre_impl.hpp