PFASST++: tests/examples/advection_diffusion/test_mpi_advection_diffusion.cpp File Reference
test_mpi_advection_diffusion.cpp File Reference
#include <algorithm>
#include <iostream>
#include <tuple>
#include <vector>
#include <gtest/gtest.h>
#include <gmock/gmock.h>
#include <mpi.h>
#include "../examples/advection_diffusion/mpi_pfasst.cpp"
Macros
#define PFASST_UNIT_TESTING
Functions
TEST (ErrorTest, MPIPFASST)
TEST (AdaptiveErrorTest, MPIPFASST)
int main (int argc, char **argv)
Macro Definition Documentation
#define PFASST_UNIT_TESTING
Definition at line 17 of file test_mpi_advection_diffusion.cpp.
Function Documentation
int main (int argc, char ** argv)
Definition at line 68 of file test_mpi_advection_diffusion.cpp.
References pfasst::init().
TEST (ErrorTest , MPIPFASST)
Definition at line 23 of file test_mpi_advection_diffusion.cpp.
References pfasst::examples::advection_diffusion::run_mpi_pfasst().
TEST (AdaptiveErrorTest , MPIPFASST)
Definition at line 43 of file test_mpi_advection_diffusion.cpp.
References pfasst::examples::advection_diffusion::run_mpi_pfasst().