PFASST++: pfasst::examples::advection_diffusion::FFT Class Reference
pfasst::examples::advection_diffusion::FFT Class Reference
Examples » Advection Diffusion
FFT helper class.
#include <fft.hpp>
Classes
struct workspace
Public Member Functions
~FFT ()
shared_ptr< workspace > get_workspace (size_t ndofs)
complex< double > * forward (const DVectorT &x)
void backward (DVectorT &x)
Private Attributes
map< size_t, shared_ptr< workspace > > workspaces
Detailed Description
FFT helper class.
Warning
Side affects galore! This is not my best work ...
Definition at line 32 of file fft.hpp.
Constructor & Destructor Documentation
pfasst::examples::advection_diffusion::FFT::~FFT () inline
Definition at line 44 of file fft.hpp.
Member Function Documentation
void pfasst::examples::advection_diffusion::FFT::backward (DVectorT & x) inline
Definition at line 79 of file fft.hpp.
References get_workspace().
Referenced by pfasst::examples::advection_diffusion::AdvectionDiffusionSweeper< time >::f_expl_eval(), pfasst::examples::advection_diffusion::AdvectionDiffusionSweeper< time >::f_impl_eval(), pfasst::examples::advection_diffusion::AdvectionDiffusionSweeper< time >::impl_solve(), and pfasst::examples::advection_diffusion::SpectralTransfer1D< time >::interpolate().
complex<double>* pfasst::examples::advection_diffusion::FFT::forward (const DVectorT & x) inline
Definition at line 69 of file fft.hpp.
References get_workspace().
Referenced by pfasst::examples::advection_diffusion::AdvectionDiffusionSweeper< time >::f_expl_eval(), pfasst::examples::advection_diffusion::AdvectionDiffusionSweeper< time >::f_impl_eval(), pfasst::examples::advection_diffusion::AdvectionDiffusionSweeper< time >::impl_solve(), and pfasst::examples::advection_diffusion::SpectralTransfer1D< time >::interpolate().
shared_ptr<workspace> pfasst::examples::advection_diffusion::FFT::get_workspace (size_t ndofs) inline
Definition at line 55 of file fft.hpp.
Referenced by backward(), forward(), and pfasst::examples::advection_diffusion::SpectralTransfer1D< time >::interpolate().
Member Data Documentation
map<size_t, shared_ptr<workspace> > pfasst::examples::advection_diffusion::FFT::workspaces private
Definition at line 41 of file fft.hpp.
The documentation for this class was generated from the following file:
examples/advection_diffusion/fft.hpp